In [1]:
from pathlib import Path
import getpass
import os
import shutil

import numpy as np
import pandas as pd

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27620\2860160806.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader
c:\Users\ASUS\Desktop\Gen AI Full stak\env\Lib\site-packages\cupy\_environment.py:284: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(
c:\Users\ASUS\Desktop\Gen AI Full stak\env\Lib\site-packages\cupy\_environment.py:284: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(

In [2]:
import os
import getpass

if not os.environ.get("GROQ_API_KEY"):
    os.environ["GROQ_API_KEY"] = getpass.getpass(
        "Enter your Groq API key: "
    )

print("Groq API key configured successfully.")

Groq API key configured successfully.

In [3]:
from pathlib import Path

PDF_PATH = Path(
    r"C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf"
)

if not PDF_PATH.exists():
    raise FileNotFoundError(
        f"PDF file was not found:\n{PDF_PATH}"
    )

print("PDF found:", PDF_PATH)

PDF found: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf

In [4]:
loader = PyPDFLoader(str(PDF_PATH))

pages = loader.load()

print(f"Total PDF pages loaded: {len(pages)}")

Total PDF pages loaded: 77

In [5]:
print("First-page metadata:")
print(pages[0].metadata)

print("\nFirst 1,000 characters:")
print(pages[0].page_content[:1000])

First-page metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1'}

First 1,000 characters:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov

In [7]:
def identify_section(paper_page: int) -> str:
    """
    Identify the major section of the Llama 2 paper
    using its printed PDF page number.
    """

    if 1 <= paper_page <= 2:
        return "front_matter"

    if 3 <= paper_page <= 4:
        return "introduction"

    if 5 <= paper_page <= 7:
        return "pretraining"

    if 8 <= paper_page <= 19:
        return "fine_tuning"

    if 20 <= paper_page <= 31:
        return "safety"

    if 32 <= paper_page <= 35:
        return "discussion"

    if paper_page == 36:
        return "conclusion"

    if 37 <= paper_page <= 45:
        return "references"

    if 46 <= paper_page <= 77:
        return "appendix"

    return "unknown"

In [8]:
for page_document in pages:
    # PyPDFLoader page index is normally zero-based
    page_index = int(page_document.metadata.get("page", 0))
    paper_page = page_index + 1

    page_document.metadata.update(
        {
            "paper": "Llama 2",
            "organization": "Meta",
            "year": 2023,
            "document_type": "research_paper",
            "paper_page": paper_page,
            "section": identify_section(paper_page),
            "access_level": "public",
        }
    )

In [9]:
for page_document in pages[:5]:
    print(page_document.metadata)

{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 1, 'page_label': '2', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 2, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 2, 'page_label': '3', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 3, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 3, 'page_label': '4', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 4, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 4, 'page_label': '5', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 5, 'section': 'pretraining', 'access_level': 'public'}

{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public'}

In [10]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    add_start_index=True,
)

chunks = text_splitter.split_documents(pages)

print(f"Total pages: {len(pages)}")
print(f"Total chunks: {len(chunks)}")

Total pages: 77
Total chunks: 343

In [11]:
for chunk_number, chunk in enumerate(chunks):
    paper_page = chunk.metadata.get("paper_page", "unknown")

    chunk.metadata["chunk_id"] = (
        f"llama2-page-{paper_page}-chunk-{chunk_number}"
    )

In [12]:
print("Chunk content:")
print(chunks[0].page_content[:1000])

print("\nChunk metadata:")
print(chunks[0].metadata)

Chunk content:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic

Chunk metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Users\\ASUS\\Desktop\\Gen AI Full stak\\class_23_chuncking\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public', 'start_index': 0, 'chunk_id': 'llama2-page-1-chunk-0'}

In [13]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-base-en-v1.5",
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True},
)

In [14]:
test_vector = embeddings.embed_query(
    "What is Llama 2?"
)

print(f"Embedding dimensions: {len(test_vector)}")
print(f"First 10 values: {test_vector[:10]}")

Embedding dimensions: 768
First 10 values: [-0.031806789338588715, -0.007344976533204317, 0.004927697125822306, -0.0058638653717935085, 0.03312014043331146, -0.03700491786003113, 0.015019138343632221, 0.02953345701098442, -0.007648929487913847, 0.0010430555557832122]

In [18]:
from pathlib import Path
import shutil

RETRIEVAL_DIR = Path(
    r"C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel"
)

PERSIST_DIRECTORY = RETRIEVAL_DIR / "chroma_llama2_retriever"

REBUILD_INDEX = True

if REBUILD_INDEX and PERSIST_DIRECTORY.exists():
    shutil.rmtree(
        PERSIST_DIRECTORY,
        ignore_errors=True
    )

print(PERSIST_DIRECTORY)

C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel\chroma_llama2_retriever

In [16]:
vector_store = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name="llama2_retriever_demo",
    persist_directory=str(PERSIST_DIRECTORY),
    collection_configuration={
        "hnsw": {
            "space": "cosine"
        }
    },
)

print("Vector store created successfully.")
print(f"Stored chunks: {len(chunks)}")
print(f"Persisted at: {PERSIST_DIRECTORY}")

Vector store created successfully.
Stored chunks: 343
Persisted at: C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel\chroma_llama2_retriever

In [19]:
from pathlib import Path

RETRIEVAL_DIR = Path(
    r"C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel"
)

PERSIST_DIRECTORY = RETRIEVAL_DIR / "chroma_llama2_retriever"

print(PERSIST_DIRECTORY)

C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel\chroma_llama2_retriever

In [20]:
PERSIST_DIRECTORY

WindowsPath('C:/Users/ASUS/Desktop/Gen AI Full stak/class_24_retrievel/chroma_llama2_retriever')

In [21]:
# Load the existing Chroma collection
vector_store = Chroma(
    collection_name="llama2_retriever_demo",
    embedding_function=embeddings,
    persist_directory=str(PERSIST_DIRECTORY),
)

print("Existing vector store loaded successfully.")
print(f"Persist directory: {PERSIST_DIRECTORY}")

Existing vector store loaded successfully.
Persist directory: C:\Users\ASUS\Desktop\Gen AI Full stak\class_24_retrievel\chroma_llama2_retriever

In [22]:
def display_documents(
    documents,
    max_characters: int = 700
) -> None:
    """
    Display retrieved LangChain Document objects clearly.
    """

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(documents, start=1):
        metadata = document.metadata

        print("=" * 90)
        print(f"RANK: {rank}")
        print(f"PAPER PAGE: {metadata.get('paper_page')}")
        print(f"SECTION: {metadata.get('section')}")
        print(f"CHUNK ID: {metadata.get('chunk_id')}")
        print(f"SOURCE: {metadata.get('source')}")
        print("-" * 90)
        print(document.page_content[:max_characters])
        print()

In [ ]:
# vector_store.similarity_search()

In [23]:
similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    }
)

In [24]:
query = "What model sizes of Llama 2 were released?"

similarity_documents = similarity_retriever.invoke(query)

display_documents(similarity_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 77
SECTION: appendix
CHUNK ID: llama2-page-77-chunk-338
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfulness and safety.
Model Dates Llama 2was trained between January 2023 and July 2023.
Status This is

==========================================================================================
RANK: 2
PAPER PAGE: 50
SECTION: appendix
CHUNK ID: llama2-page-50-chunk-228
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Falcon 7B 21.2 21.7 22.3 16.1 17.3 20.4 26.2 23.8 26.4
Falcon 40B 37.0 18.5 36.4 19.6 40.2 45.7 58.7 58.7 32.7
Llama 1
7B 23.9 18.9 24.6 26.1 19.2 21.9 33.0 32.5 22.3
13B 33.9 20.1 34.9 22.2 31.6 39.8 52.9 45.1 29.5
33B 41.7 18.9 37.3 18.7 48.0 59.5 74.8 44.7 35.0
65B 47.6 23.6 42.1 23.9 56.7 63.6 83.0 48.1 41.8
Llama 2
7B 29.3 23.2 31.0 23.9 22.4 32.7 43.2 37.4 28.2
13B 39.1 21.7 38.1 23.0 41.0 54.6 62.1 46.1 27.3
34B 43.4 19.3 40.7 21.3 47.5 62.1 77.2 49.0 32.7
70B 54.2 23.2 48.8 25.7 70.2 76.6 86.9 53.4 41.8
Table 24: Comparison to open source models on AGI Eval (English)
50

==========================================================================================
RANK: 3
PAPER PAGE: 49
SECTION: appendix
CHUNK ID: llama2-page-49-chunk-224
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 1
7B 76.5 79.8 48.9 76.1 70.1 72.8 47.6 57.2 33.6 35.1
13B 78.1 80.1 50.4 79.2 73.0 74.8 52.7 56.4 62.0 46.9
33B 83.1 82.3 50.4 82.8 76.0 80.0 57.8 58.6 72.5 57.8
65B 85.3 82.8 52.3 84.2 77.0 78.9 56.0 60.2 74.0 63.4
Llama 2
7B 77.4 78.8 48.3 77.2 69.2 75.2 45.9 58.6 57.8 45.3
13B 81.7 80.5 50.3 80.7 72.8 77.3 49.4 57.0 67.3 54.8
34B 83.7 81.9 50.9 83.3 76.7 79.4 54.5 58.2 74.3 62.6
70B 85.0 82.8 50.7 85.3 80.2 80.2 57.4 60.2 78.5 68.9
Table 20: Performance on standard benchmarks.
Human-Eval MBPP
pass@1 pass@100 pass@1 pass@80
MPT 7B 18.3 - 22.6 -
30B 25.0 - 32.8 -
Falcon 7B 0.0 - 11.2 -
40B 0.6 - 29.8 -
Llama 1
7B 10.5 36.5 17.7 56.2
13B 15.8 52.5 22.0 64.0
33B 21.7 70.7 30.2 73.4
65B

==========================================================================================
RANK: 4
PAPER PAGE: 74
SECTION: appendix
CHUNK ID: llama2-page-74-chunk-323
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 1
7B 0.27 0.26 0.34 0.54 0.36 0.39 0.26 0.28 0.33 0.45 0.33 0.17 0.24 0.31 0.44 0.57 0.39 0.3513B 0.24 0.24 0.31 0.52 0.37 0.37 0.23 0.28 0.31 0.50 0.27 0.10 0.24 0.27 0.41 0.55 0.34 0.2533B 0.23 0.26 0.34 0.50 0.36 0.35 0.24 0.33 0.34 0.49 0.31 0.12 0.23 0.30 0.41 0.60 0.28 0.2765B 0.25 0.26 0.34 0.46 0.36 0.40 0.25 0.32 0.32 0.48 0.31 0.11 0.25 0.30 0.43 0.60 0.39 0.34
Llama 2
7B 0.28 0.25 0.29 0.50 0.36 0.37 0.21 0.34 0.32 0.50 0.28 0.19 0.26 0.32 0.44 0.51 0.30 0.2513B 0.24 0.25 0.35 0.50 0.41 0.36 0.24 0.39 0.35 0.48 0.31 0.18 0.27 0.34 0.46 0.66 0.35 0.2834B 0.27 0.24 0.33 0.56 0.41 0.36 0.26 0.32 0.36 0.53 0.33 0.07 0.26 0.30 0.45 0.56 0.26 0.3570B 0.31 0.29 0.35 0.51 0.41 0.45

In [26]:
mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

In [27]:
query = "How was Llama 2-Chat trained and aligned?"

mmr_documents = mmr_retriever.invoke(query)

display_documents(mmr_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-29
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost Attention (GAtt), which we find helps control dialogue flow over multiple turns
(Section 3.3). See Se

==========================================================================================
RANK: 2
PAPER PAGE: 54
SECTION: appendix
CHUNK ID: llama2-page-54-chunk-239
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Dialogue Turn Baseline + GAtt
2 100% 100%
4 10% 100%
6 0% 100%
20 0% 100%
Table 30: GAtt results.Llama 2-Chat with GAtt is able to refer to attributes 100% of the time, for up to 20
turns from our human evaluation. We limited the evaluated attributes to public figures and hobbies.
The attention now spans beyond 20 turns.We tested the model ability to remember the system arguments
troughahumanevaluation. Thearguments(e.g. hobbies, persona)aredefinedduringthefirstmessage, and
then from turn 2 to 20. We explicitly asked the model to refer to them (e.g. “What is your favorite hobby?”,
“What is your name?”), to measure the multi-turn memory ability ofLlama 2-Chat. We report the results
in Table 3

==========================================================================================
RANK: 3
PAPER PAGE: 34
SECTION: discussion
CHUNK ID: llama2-page-34-chunk-147
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
knowledge updates post-pretraining, potential for non-factual generation such as unqualified advice, and a
propensity towards hallucinations.
Furthermore, our initial version ofLlama 2-Chat predominantly concentrated on English-language data.
While our experimental observations suggest the model has garnered some proficiency in other languages,
its proficiency is limited, due primarily to the limited amount of pretraining data available in non-English
languages (as documented in Table 10). Consequently, the model’s performance in languages other than
English remains fragile and should be used with caution.
Like other LLMs,Llama 2 may generate harmful, offensive, or biased content due to its

==========================================================================================
RANK: 4
PAPER PAGE: 56
SECTION: appendix
CHUNK ID: llama2-page-56-chunk-247
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 2-Chat, ChatGPT,
PaLM-chat, Falcon
You are a helpful, respectful and honest assistant. Always answer as helpfully
as possible, while being safe. Your answers should not include any harmful,
unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that
your responses are socially unbiased and positive in nature.
If a question does not make any sense, or is not factually coherent, explain why
instead of answering something not correct. If you don’t know the answer to a
question, please don’t share false information.
MPT
<|im_start|> system
A conversation between a user and an LLM-based AI assistant. The assistant
gives helpful and honest answers.<|im_end|>
Vicuna
A

In [28]:
query = "How was Llama 2-Chat trained and aligned?"

similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}
)

mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

similarity_results = similarity_retriever.invoke(query)
mmr_results = mmr_retriever.invoke(query)

In [29]:
print("Similarity Search results:")
for document in similarity_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

print("\nMMR results:")
for document in mmr_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

Similarity Search results:
8 fine_tuning llama2-page-8-chunk-29
18 fine_tuning llama2-page-18-chunk-77
4 introduction llama2-page-4-chunk-13
4 introduction llama2-page-4-chunk-12

MMR results:
8 fine_tuning llama2-page-8-chunk-29
54 appendix llama2-page-54-chunk-239
34 discussion llama2-page-34-chunk-147
56 appendix llama2-page-56-chunk-247

In [30]:
threshold_retriever = vector_store.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={
        "k": 10,
        "score_threshold": 0.64,
    }
)

In [31]:
query = "What safety techniques were used for Llama 2-Chat?"

threshold_documents = threshold_retriever.invoke(query)

display_documents(threshold_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 4
SECTION: introduction
CHUNK ID: llama2-page-4-chunk-13
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), approach to model safety (Section 4), key observations and insights (Section 5), relevant related
wor

==========================================================================================
RANK: 2
PAPER PAGE: 4
SECTION: introduction
CHUNK ID: llama2-page-4-chunk-11
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Figure 3: Safety human evaluation results forLlama 2-Chat compared to other open-source and closed-
source models. Human raters judged model generations for safety violations across ~2,000 adversarial
prompts consisting of both single and multi-turn prompts. More details can be found in Section 4.4. It is
important to caveat these safety results with the inherent bias of LLM evaluations due to limitations of the
prompt set, subjectivity of the review guidelines, and subjectivity of individual raters. Additionally, these
safety evaluations are performed using content standards that are likely to be biased towards theLlama
2-Chatmodels.
We are releasing the following models to the general publ

==========================================================================================
RANK: 3
PAPER PAGE: 30
SECTION: safety
CHUNK ID: llama2-page-30-chunk-131
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
(a) Overall violation percentage.
 (b)Overall safety and helpfulness mean rating.
Figure 17: Overall safety measures.Left: Llama 2-Chat has low violation percentage overall across model
sizes. Right: Llama 2-Chat has high safety and helpfulness mean rating overall across model sizes. It is
important to note that these results are subject to limitations of the prompt set, subjectivity of the review
guidelines, and subjectivity of individual raters.
• 1 - Severe safety violations
We consider a rating of 1 or 2 as violation and use violation percentage as our main evaluation metric, with
the mean rating as a supplement. Each example is annotated by three annotators and we take the majority
vote

==========================================================================================
RANK: 4
PAPER PAGE: 30
SECTION: safety
CHUNK ID: llama2-page-30-chunk-132
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
reliability (IRR) as in the helpfulness human evaluation. The IRR scores range from0.70to0.95 depending
on the annotation batch, indicating a high degree of agreement among annotators on safety assessments.
On Llama 2-Chat annotations, the average IRR is0.92 according to Gwet’s AC2 measure. We see lower IRR
scoresonbatcheswherethemodelshaveahighviolationrate(e.g.,Vicuna)andhigherIRRscoresonbatches
where the models have relatively low violation rates (e.g.,Llama 2-Chat, Falcon, and ChatGPT).
Figure 18: Single-turn and multi-turn violation percentage.Note that these results should be interpreted
carefully due to limitations of the prompt set, subjectivity of the review guidelines, content stan

==========================================================================================
RANK: 5
PAPER PAGE: 58
SECTION: appendix
CHUNK ID: llama2-page-58-chunk-253
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in either case.
A.4 Additional Details for Safety
A.4.1 Tension between Safety and Helpfulness in Reward Modeling
WebrieflydiscussedthetensionbetweensafetyandhelpfulnessinSection3.2.2andhowitleadstooptimizin

==========================================================================================
RANK: 6
PAPER PAGE: 30
SECTION: safety
CHUNK ID: llama2-page-30-chunk-133
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
We show the overall violation percentage and safety rating of various LLMs in Figure 17.Llama 2-Chat has
comparableorloweroverallviolationpercentageacrossmodelsizes,whileChatGPTandFalcon(Almazrouei
et al., 2023) come next, then MPT (MosaicML NLP Team et al., 2023) and Vicuna (Chiang et al., 2023). It is
important to interpret these results carefully, as they are affected by limitations of the prompt set, subjectivity
of the review guidelines, content standards, and subjectivity of individual raters. Upon manual analysis, we
found that the response of Falcon is typically short (one or two sentences), thus less prone to generating
unsafe content but also generally less helpful. This is reflect

==========================================================================================
RANK: 7
PAPER PAGE: 3
SECTION: introduction
CHUNK ID: llama2-page-3-chunk-10
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
continue to improve the safety of those models, paving the way for more responsible development of LLMs.
We also share novel observations we made during the development ofLlama 2 and Llama 2-Chat, such as
the emergence of tool usage and temporal organization of knowledge.
3

==========================================================================================
RANK: 8
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-29
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost Attention (GAtt), which we find helps control dialogue flow over multiple turns
(Section 3.3). See Se

==========================================================================================
RANK: 9
PAPER PAGE: 58
SECTION: appendix
CHUNK ID: llama2-page-58-chunk-255
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Here we showcase a few samples to qualitatively examine the evolution of model behavior when we scale
safetydatainTables36,37,and38. Ingeneral,weareobservingthat Llama 2-Chatbecomessaferresponding
to unsafe prompts with more safety data used. For example,Llama 2-Chat learns to refuse to generate
offensive content (Table 36) once we use 50% of safety data. In the meantime, we also observe thatLlama
2-Chatstarts to be behave more conservatively when there are offensive (e.g., abomination in Table 37) or
sensitive words (e.g., “sex in a pan” in Table 38) in prompts, even if the prompts themselves are safe (e.g.,
sex in a pan is the name of a dessert).
A.4.3 English Pronouns
The terms that we us

==========================================================================================
RANK: 10
PAPER PAGE: 70
SECTION: appendix
CHUNK ID: llama2-page-70-chunk-311
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 2-Chat
7B 57.04 60.59 96.45
13B 62.18 65.73 96.45
34B 67.2 70.01 97.06
70B 64.14 67.07 97.06
Table 44: Evaluation results on TruthfulQA across different model generations.
Limitations of Benchmarks. It is important to note that these evaluations using automatic metrics are by
no means fully comprehensive, due to the complex nature of toxicity and bias in LLMs, but the benchmarks
we selected are representative of our understanding thatLlama 2-Chat improves on critical aspects of LLM
safety. Benchmark evaluation is important for assessing AI models, including chat-oriented LLMs, because
benchmarks provide a standardized and measurable way to compare different models and track progress in

In [32]:
# threshold_retriever = vector_store.as_retriever(
#     search_type="similarity_score_threshold",
#     search_kwargs={
#         "k": 10,
#         "score_threshold": 0.35,
#     }

In [33]:
query = "What safety techniques were used for Llama 2-Chat?"

scored_results = vector_store.similarity_search_with_relevance_scores(
    query=query,
    k=5,
)

for rank, (document, relevance_score) in enumerate(
    scored_results,
    start=1
):
    print("=" * 90)
    print(f"Rank: {rank}")
    print(f"Relevance score: {relevance_score:.4f}")
    print(f"Paper page: {document.metadata.get('paper_page')}")
    print(f"Section: {document.metadata.get('section')}")
    print(document.page_content[:500])

==========================================================================================
Rank: 1
Relevance score: 0.8076
Paper page: 4
Section: introduction
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of
==========================================================================================
Rank: 2
Relevance score: 0.7312
Paper page: 4
Section: introduction
Figure 3: Safety human evaluation results forLlama 2-Chat compared to other open-source and closed-
source models. Human raters judged model generations for safety violations across ~2,000 adversarial
prompts consisting of both single and multi-turn prompts. More details can be found in Section 4.4. It is
important to caveat these safety results with the inherent bias of LLM evaluations due to limitations of the
prompt set, subjectivity of the review guidelines, and subjectivity of individual ra
==========================================================================================
Rank: 3
Relevance score: 0.7302
Paper page: 30
Section: safety
(a) Overall violation percentage.
 (b)Overall safety and helpfulness mean rating.
Figure 17: Overall safety measures.Left: Llama 2-Chat has low violation percentage overall across model
sizes. Right: Llama 2-Chat has high safety and helpfulness mean rating overall across model sizes. It is
important to note that these results are subject to limitations of the prompt set, subjectivity of the review
guidelines, and subjectivity of individual raters.
• 1 - Severe safety violations
We consider a rat
==========================================================================================
Rank: 4
Relevance score: 0.7285
Paper page: 30
Section: safety
reliability (IRR) as in the helpfulness human evaluation. The IRR scores range from0.70to0.95 depending
on the annotation batch, indicating a high degree of agreement among annotators on safety assessments.
On Llama 2-Chat annotations, the average IRR is0.92 according to Gwet’s AC2 measure. We see lower IRR
scoresonbatcheswherethemodelshaveahighviolationrate(e.g.,Vicuna)andhigherIRRscoresonbatches
where the models have relatively low violation rates (e.g.,Llama 2-Chat, Falcon, and ChatGPT).
Figu
==========================================================================================
Rank: 5
Relevance score: 0.7244
Paper page: 58
Section: appendix
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in eith

In [34]:
metric_query = "How was reinforcement learning with human feedback used?"

candidate_documents = vector_store.similarity_search(
    metric_query,
    k=6,
)

candidate_texts = [
    document.page_content
    for document in candidate_documents
]

print(f"Candidate chunks selected: {len(candidate_texts)}")

Candidate chunks selected: 6

In [35]:
query_vector = np.asarray(
    embeddings.embed_query(metric_query),
    dtype=np.float64,
)

document_vectors = np.asarray(
    embeddings.embed_documents(candidate_texts),
    dtype=np.float64,
)

print("Query-vector shape:", query_vector.shape)
print("Document-vectors shape:", document_vectors.shape)

Query-vector shape: (768,)
Document-vectors shape: (6, 768)

In [36]:
def cosine_similarity(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    denominator = (
        np.linalg.norm(vector_a)
        * np.linalg.norm(vector_b)
    )

    if denominator == 0:
        return 0.0

    return float(
        np.dot(vector_a, vector_b) / denominator
    )


def euclidean_distance(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.linalg.norm(vector_a - vector_b)
    )


def dot_product(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.dot(vector_a, vector_b)
    )

In [37]:
metric_rows = []

for document, document_vector in zip(
    candidate_documents,
    document_vectors
):
    metric_rows.append(
        {
            "paper_page": document.metadata.get("paper_page"),
            "section": document.metadata.get("section"),
            "chunk_id": document.metadata.get("chunk_id"),
            "cosine_similarity": cosine_similarity(
                query_vector,
                document_vector
            ),
            "euclidean_distance": euclidean_distance(
                query_vector,
                document_vector
            ),
            "dot_product": dot_product(
                query_vector,
                document_vector
            ),
            "preview": document.page_content[:100].replace(
                "\n",
                " "
            ),
        }
    )

metric_table = pd.DataFrame(metric_rows)

metric_table

,paper_page,section,chunk_id,cosine_similarity,euclidean_distance,dot_product,preview
0,5,pretraining,llama2-page-5-chunk-14,0.759080,0.694147,0.759080,Figure 4: Training ofLlama 2-Chat: This proces...
1,2,front_matter,llama2-page-2-chunk-3,0.748611,0.709068,0.748611,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
2,10,fine_tuning,llama2-page-10-chunk-35,0.741688,0.718766,0.741688,"sampled human preferences, whereby human annot..."
3,9,fine_tuning,llama2-page-9-chunk-34,0.732295,0.731717,0.732295,"learning rate of2 × 10−5, a weight decay of 0...."
4,36,conclusion,llama2-page-36-chunk-157,0.714277,0.755940,0.714277,"In this paradigm, models are fine-tuned based ..."
5,32,discussion,llama2-page-32-chunk-138,0.711838,0.759161,0.711838,"bility, seemed a somewhat shadowy field for th..."

In [38]:
metric_query

'How was reinforcement learning with human feedback used?'

In [39]:
metric_table.sort_values(
    by="cosine_similarity",
    ascending=False
)[
    [
        "paper_page",
        "section",
        "cosine_similarity",
        "preview",
    ]
]

,paper_page,section,cosine_similarity,preview
0,5,pretraining,0.759080,Figure 4: Training ofLlama 2-Chat: This proces...
1,2,front_matter,0.748611,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
2,10,fine_tuning,0.741688,"sampled human preferences, whereby human annot..."
3,9,fine_tuning,0.732295,"learning rate of2 × 10−5, a weight decay of 0...."
4,36,conclusion,0.714277,"In this paradigm, models are fine-tuned based ..."
5,32,discussion,0.711838,"bility, seemed a somewhat shadowy field for th..."

In [40]:
metric_table.sort_values(
    by="euclidean_distance",
    ascending=True
)[
    [
        "paper_page",
        "section",
        "euclidean_distance",
        "preview",
    ]
]

,paper_page,section,euclidean_distance,preview
0,5,pretraining,0.694147,Figure 4: Training ofLlama 2-Chat: This proces...
1,2,front_matter,0.709068,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
2,10,fine_tuning,0.718766,"sampled human preferences, whereby human annot..."
3,9,fine_tuning,0.731717,"learning rate of2 × 10−5, a weight decay of 0...."
4,36,conclusion,0.755940,"In this paradigm, models are fine-tuned based ..."
5,32,discussion,0.759161,"bility, seemed a somewhat shadowy field for th..."

In [41]:
metric_table.sort_values(
    by="dot_product",
    ascending=False
)[
    [
        "paper_page",
        "section",
        "dot_product",
        "preview",
    ]
]

,paper_page,section,dot_product,preview
0,5,pretraining,0.759080,Figure 4: Training ofLlama 2-Chat: This proces...
1,2,front_matter,0.748611,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
2,10,fine_tuning,0.741688,"sampled human preferences, whereby human annot..."
3,9,fine_tuning,0.732295,"learning rate of2 × 10−5, a weight decay of 0...."
4,36,conclusion,0.714277,"In this paradigm, models are fine-tuned based ..."
5,32,discussion,0.711838,"bility, seemed a somewhat shadowy field for th..."

In [42]:
normalized_query_vector = (
    query_vector / np.linalg.norm(query_vector)
)

normalized_document_vectors = (
    document_vectors
    / np.linalg.norm(
        document_vectors,
        axis=1,
        keepdims=True
    )
)

normalized_dot_scores = (
    normalized_document_vectors
    @ normalized_query_vector
)

cosine_scores = np.asarray(
    [
        cosine_similarity(
            query_vector,
            document_vector
        )
        for document_vector in document_vectors
    ]
)

print("Cosine scores:")
print(cosine_scores)

print("\nDot product after normalization:")
print(normalized_dot_scores)

print(
    "\nAre they approximately equal?",
    np.allclose(
        cosine_scores,
        normalized_dot_scores,
        atol=1e-8,
    ),
)

Cosine scores:
[0.75907992 0.74861139 0.74168801 0.73229509 0.71427736 0.71183763]

Dot product after normalization:
[0.75907992 0.74861139 0.74168801 0.73229509 0.71427736 0.71183763]

Are they approximately equal? True

In [43]:
fine_tuning_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "section": "fine_tuning"
        },
    }
)

In [44]:
query = "How was Llama 2-Chat aligned with human preferences?"

fine_tuning_documents = fine_tuning_retriever.invoke(query)

display_documents(fine_tuning_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 18
SECTION: fine_tuning
CHUNK ID: llama2-page-18-chunk-77
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for judging models for natural language generation,
including dialogue models. To evaluate the quality of

==========================================================================================
RANK: 2
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-38
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model
on-distribution and maintain an accur

==========================================================================================
RANK: 3
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-29
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost Attention (GAtt), which we find helps control dialogue flow over multiple turns
(Section 3.3). See Se

==========================================================================================
RANK: 4
PAPER PAGE: 19
SECTION: fine_tuning
CHUNK ID: llama2-page-19-chunk-79
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generation comparison. High IRR scores (closer to 1.0) are typically seen as
better from a data quality persp

In [45]:
for document in fine_tuning_documents:
    assert document.metadata["section"] == "fine_tuning"

print("All returned documents are from the fine_tuning section.")

All returned documents are from the fine_tuning section.

In [46]:
filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "$and": [
                {
                    "section": {
                        "$eq": "fine_tuning"
                    }
                },
                {
                    "year": {
                        "$eq": 2023
                    }
                },
                {
                    "organization": {
                        "$eq": "Meta"
                    }
                },
            ]
        },
    }
)

In [47]:
query = "How was human preference data collected?"

filtered_documents = filtered_retriever.invoke(query)

display_documents(filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-35
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
sampled human preferences, whereby human annotators select which of two model outputs they prefer.
This human feedback is subsequently used to train a reward model, which learns patterns in the preferences
of the human annotators and can then automate preference decisions.
3.2.1 Human Preference Data Collection
Next, we collect human preference data for reward modeling. We chose a binary comparison protocol over
other schemes, mainly because it enables us to maximize the diversity of collected prompts. Still, other
strategies are worth considering, which we leave for future work.
Our annotation procedure proceeds as follows. We ask annotators to first write a prompt, then choose
between two

==========================================================================================
RANK: 2
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-41
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Dataset
Num. of
Comparisons
Avg. # Turns
per Dialogue
Avg. # Tokens
per Example
Avg. # Tokens
in Prompt
Avg. # Tokens
in Response
Anthropic Helpful 122,387 3.0 251.5 17.7 88.4
Anthropic Harmless 43,966 3.0 152.5 15.7 46.4
OpenAI Summarize 176,625 1.0 371.1 336.0 35.1
OpenAI WebGPT 13,333 1.0 237.2 48.3 188.9
StackExchange 1,038,480 1.0 440.2 200.1 240.2
Stanford SHP 74,882 1.0 338.3 199.5 138.8
Synthetic GPT-J 33,139 1.0 123.3 13.0 110.3
Meta (Safety & Helpfulness) 1,418,091 3.9 798.5 31.4 234.1
Total 2,919,326 1.6 595.7 108.2 216.9
Table 6: Statistics of human preference data for reward modeling.We list both the open-source and
internally collected human preference data used for reward mode

==========================================================================================
RANK: 3
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-39
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
against multiple open-source preference datasets including Anthropic Helpful and Harmless (Bai et al.,
2022a), OpenAI Summarize (Stiennon et al., 2020), OpenAI WebGPT (Nakano et al., 2021), StackExchange
(Lambert et al., 2023), Stanford Human Preferences (Ethayarajh et al., 2022), and Synthetic GPT-J (Havrilla).
We collected a large dataset of over 1 million binary comparisons based on humans applying our specified
guidelines, which we refer to asMetareward modeling data. Note that the number of tokens in prompts and
answers differs depending on the text domain. Summarization and online forum data generally have longer
prompts, while dialogue-style prompts are usually shorter. Compared to ex

==========================================================================================
RANK: 4
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-38
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model
on-distribution and maintain an accur

Prefilter

In [48]:
pre_filter = {
    "$and": [
        {
            "section": {
                "$eq": "fine_tuning"
            }
        },
        {
            "year": {
                "$eq": 2023
            }
        },
    ]
}

pre_filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": pre_filter,
    }
)

pre_filtered_documents = pre_filtered_retriever.invoke(
    "How was the reward model trained?"
)

display_documents(pre_filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-40
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we train two separate reward
models, one optimized for helpfulness (referred to asHelpfulness RM) and anoth

==========================================================================================
RANK: 2
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-54
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
evaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.
Therefore, everything else being equal, an improvement of the reward model can be directly translated into
an improvement forLlama 2-Chat.
3.2.3 Iterative Fine-Tuning
As we received more batches of human preference data annotation, we were able to train better reward
models and collect more prompts. We therefore trained successive versions for RLHF models, referred to
here as RLHF-V1, ..., RLHF-V5.
We explored RLHF fine-tuning with two main algorithms:
• Proximal Policy Optimization (PPO)(Schulman et al., 2017), the standard in RLHF literature.
• RejectionSamplingfine-tuning . Wesampl

==========================================================================================
RANK: 3
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 4
PAPER PAGE: 12
SECTION: fine_tuning
CHUNK ID: llama2-page-12-chunk-46
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Helpfulness reward model is eventually trained on all Meta Helpfulness data, combined with an equal
parts of the remaining data uniformly sampled from Meta Safety and from the open-source datasets. The
Meta Safety reward model is trained on all Meta Safety and Anthropic Harmless data, mixed with Meta
Helpfulness and open-source helpfulness data in a 90/10 proportion. We found that the setting with 10%
helpfulness data is especially beneficial for the accuracy on samples where both the chosen and rejected
responses were deemed safe.
Training Details. We train for one epoch over the training data. In earlier experiments, we found that
training longer can lead to over-fitting. We use the same o

Post-Filtering

In [49]:
unfiltered_candidates = vector_store.similarity_search(
    query="How was the reward model trained?",
    k=15,
)

In [50]:
post_filtered_documents = [
    document
    for document in unfiltered_candidates
    if document.metadata.get("section") == "fine_tuning"
    and document.metadata.get("year") == 2023
]

display_documents(post_filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-40
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we train two separate reward
models, one optimized for helpfulness (referred to asHelpfulness RM) and anoth

==========================================================================================
RANK: 2
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-54
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
evaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.
Therefore, everything else being equal, an improvement of the reward model can be directly translated into
an improvement forLlama 2-Chat.
3.2.3 Iterative Fine-Tuning
As we received more batches of human preference data annotation, we were able to train better reward
models and collect more prompts. We therefore trained successive versions for RLHF models, referred to
here as RLHF-V1, ..., RLHF-V5.
We explored RLHF fine-tuning with two main algorithms:
• Proximal Policy Optimization (PPO)(Schulman et al., 2017), the standard in RLHF literature.
• RejectionSamplingfine-tuning . Wesampl

==========================================================================================
RANK: 3
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 4
PAPER PAGE: 12
SECTION: fine_tuning
CHUNK ID: llama2-page-12-chunk-46
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Helpfulness reward model is eventually trained on all Meta Helpfulness data, combined with an equal
parts of the remaining data uniformly sampled from Meta Safety and from the open-source datasets. The
Meta Safety reward model is trained on all Meta Safety and Anthropic Harmless data, mixed with Meta
Helpfulness and open-source helpfulness data in a 90/10 proportion. We found that the setting with 10%
helpfulness data is especially beneficial for the accuracy on samples where both the chosen and rejected
responses were deemed safe.
Training Details. We train for one epoch over the training data. In earlier experiments, we found that
training longer can lead to over-fitting. We use the same o

==========================================================================================
RANK: 5
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-38
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model
on-distribution and maintain an accur

==========================================================================================
RANK: 6
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-55
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
with our reward, consistent with Bai et al. (2022b). The same re-ranking strategy for LLMs was also
proposed inDeng et al. (2019), where the rewardis seen asan energy function. Here, we go onestep
further, and use the selected outputs for a gradient update. For each prompt, the sample obtaining
13

==========================================================================================
RANK: 7
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-53
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume of data annotation used for training, a signal that there is
room for more improvement with more ann

==========================================================================================
RANK: 8
PAPER PAGE: 17
SECTION: fine_tuning
CHUNK ID: llama2-page-17-chunk-73
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
system message during the conversation by integrating such data during fine-tuning.
3.4 RLHF Results
3.4.1 Model-Based Evaluation
Evaluating LLMs is a challenging open-research problem. Human evaluation, while a gold standard, can
be complicated by various HCI considerations (Clark et al., 2021; Gehrmann et al., 2023), and is not always
scalable. Thus, to select the best-performing models among several ablations at each iteration from RLHF-V1
to V5, we first observed the improvement of the rewards from the latest reward models, to save costs and
increase iteration speed. We later validated major model versions with human evaluations.
How Far Can Model-Based Evaluation Go?To measure the robus

==========================================================================================
RANK: 9
PAPER PAGE: 14
SECTION: fine_tuning
CHUNK ID: llama2-page-14-chunk-56
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
100 101
N Samples
0.54
0.56
0.58
0.60
0.62
0.64
0.66Reward Score
Max of the rewards
Median of the rewards
Figure 7: Max and median reward among N samples, N ∈ [1, . . . ,100] averaged over our training set of
prompts. The delta between max and median can be interpreted as potential gain with Rejection Sampling.
the highest reward score is considered the new gold standard. Similar to Scialom et al. (2020a), we
then fine-tune our model on the new set of ranked samples, reinforcing the reward.
The two RL algorithms mainly differ in:
• Breadth— in Rejection Sampling, the model exploresK samples for a given prompt, while only one
generation is done for PPO.
• Depth— in PPO, during training at ste

==========================================================================================
RANK: 10
PAPER PAGE: 9
SECTION: fine_tuning
CHUNK ID: llama2-page-9-chunk-34
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
learning rate of2 × 10−5, a weight decay of 0.1, a batch size of 64, and a sequence length of 4096 tokens.
For the fine-tuning process, each sample consists of a prompt and an answer. To ensure the model sequence
length is properly filled, we concatenate all the prompts and answers from the training set. A special token is
utilized to separate the prompt and answer segments. We utilize an autoregressive objective and zero-out
the loss on tokens from the user prompt, so as a result, we backpropagate only on answer tokens. Finally, we
fine-tune the model for 2 epochs.
3.2 Reinforcement Learning with Human Feedback (RLHF)
RLHF is a model training procedure that is applied to a fine-tuned langua

==========================================================================================
RANK: 11
PAPER PAGE: 14
SECTION: fine_tuning
CHUNK ID: llama2-page-14-chunk-58
SOURCE: C:\Users\ASUS\Desktop\Gen AI Full stak\class_23_chuncking\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
reward_max (T=1)
reward_max (T=1.1)
reward_max (T=1.2)
reward_max (T=1.3)
reward_max (T=1.4)
reward_max (T=1.5)
Figure8: RLHFimpactofthetemperature whensamplingNoutputsandscoringthemwitharewardmodel.
Rejection Sampling. We perform rejection sampling only with our largest 70BLlama 2-Chat. All smaller
models are fine-tuned on rejection sampled data from the larger model, thus distilling the large-model
capabilities into the smaller ones. We leave further analysis of the effect of this distillation for future work.
At each iterative stage, we sampleK answers for each prompt from the most recent model. We score each
sample given the best reward model accessible at the time of the experiment, and

In [51]:
print(
    "Documents retrieved before post-filtering:",
    len(unfiltered_candidates),
)

print(
    "Documents remaining after post-filtering:",
    len(post_filtered_documents),
)

Documents retrieved before post-filtering: 15
Documents remaining after post-filtering: 11

In [56]:


from langchain_groq import ChatGroq

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0
)

question = "What are the main components of Llama 2?"

docs = vector_store.similarity_search(
    question,
    k=3
)

context = "\n\n".join(
    doc.page_content for doc in docs
)

prompt = f"""
Answer the question using only the context below.

Context:
{context}

Question:
{question}
"""

response = llm.invoke(prompt)

print(response.content)

The model card for Llama 2 lists the following key components:

| Component | Details (as given in the card) |
|-----------|--------------------------------|
| **Model Developers** | Meta AI |
| **Variations** | Llama 2 is released in several parameter sizes – 7 B, 13 B, and 70 B – and includes both pretrained and fine‑tuned versions. |
| **Input** | The model accepts **text only**. |
| **Output** | The model generates **text only**. |
| **Model Architecture** | An **auto‑regressive language model** that uses an optimized Transformer architecture. The fine‑tuned versions are trained with supervised fine‑tuning (SFT) and reinforcement learning with human feedback (RLHF) to improve helpfulness and safety. |
| **Model Dates** | Trained between **January 2023 and July 2023**. |
| **Status** | A **static model** trained on an offline dataset; future tuned versions will be released as safety improvements are made. |
| **License** | Available under a **custom commercial license** (see ai.meta.com/resources/models-and‑libraries/llama‑downloads/). |
| **Where to send comments** | (Provided in the card, but the specific address is omitted here). |

These sections together constitute the main components described for Llama 2 in the provided model card.

05-Aug-2026

In [57]:
import os
from typing import List

from pydantic import BaseModel, Field

from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers.ensemble import EnsembleRetriever

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from langchain_classic.retrievers.contextual_compression import (
    ContextualCompressionRetriever,
)
from langchain_classic.retrievers.document_compressors import (
    CrossEncoderReranker,
)
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

In [58]:
def display_documents(
    documents,
    title: str = "Retrieved Documents",
    max_documents: int = 10,
    max_characters: int = 600,
) -> None:
    """Display retrieved LangChain Document objects."""

    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(
        documents[:max_documents],
        start=1,
    ):
        metadata = document.metadata

        print(f"\nRANK: {rank}")
        print(f"Paper page: {metadata.get('paper_page')}")
        print(f"Section: {metadata.get('section')}")
        print(f"Chunk ID: {metadata.get('chunk_id')}")
        print("-" * 100)
        print(document.page_content[:max_characters])

In [59]:
def deduplicate_documents(documents):
    """Remove duplicate retrieved chunks while preserving their order."""

    unique_documents = []
    seen_keys = set()

    for document in documents:
        key = (
            document.metadata.get("chunk_id")
            or (
                document.metadata.get("source"),
                document.metadata.get("page"),
                document.page_content,
            )
        )

        if key not in seen_keys:
            seen_keys.add(key)
            unique_documents.append(document)

    return unique_documents

In [60]:
from langchain_community.retrievers import BM25Retriever

In [61]:
bm25_retriever = BM25Retriever.from_documents(chunks)

In [62]:
bm25_retriever

BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x000001AF30EB1410>)

In [63]:
# Final number of results
bm25_retriever.k = 4

In [64]:
sparse_query = "Grouped-Query Attention GQA 70B"

In [65]:
sparse_documents = bm25_retriever.invoke(sparse_query)

In [66]:
display_documents(
    sparse_documents,
    title="Sparse Retrieval: BM25 Results",
)

====================================================================================================
Sparse Retrieval: BM25 Results
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 2
Paper page: 48
Section: appendix
Chunk ID: llama2-page-48-chunk-220
----------------------------------------------------------------------------------------------------
BoolQ PIQA SIQA Hella-Swag ARC-e ARC-c NQ TQA MMLU GSM8K Human-Eval
MHA 71.0 79.3 48.2 75.1 71.2 43.0 12.4 44.7 28.0 4.9 7.9
MQA 70.6 79.0 47.9 74.5 71.6 41.9 14.5 42.8 26.5 4.8 7.3
GQA 69.4 78.8 48.6 75.4 72.1 42.5 14.0 46.2 26.9 5.3 7.9
Table 18: Attention architecture ablations.We report 0-shot results for all tasks except MMLU(5-shot) and
GSM8K(8-shot). For GSM8K and Human-Eval we report maj@1 and pass@1 results. For NQ and TriviaQA
we report EM. For all other tasks we report accuracy.
Figure 24: Multi-query variants enable higher throughput with larger batch sizes, and show similar
latenc

RANK: 3
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 4
Paper page: 48
Section: appendix
Chunk ID: llama2-page-48-chunk-221
----------------------------------------------------------------------------------------------------
memory error at a batch size of 1024 for a context of 256 tokens and at a batch size of 128 for 2k context,
whereas MQA and GQA have successful runs in those settings.
Therefore, based on the ablation results and ease of scaling inference, for the 34B and 70BLlama 2 models
we chose to use GQA instead of MQA.
Figure 24 shows how inference speed changed for the 30B GQA and MQA ablation models compared to the
MHA baseline, in an experiment using 8 x 80 GiB A100s with tensor parallelism. In these runs we simply
duplicated the KV heads for MQA in all GPUs, so the KV cache size for MQA became equal

In [67]:
dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    },
)

In [68]:
dense_query = (
    "How did Meta improve inference scalability "
    "for the largest Llama 2 models?"
)

dense_documents = dense_retriever.invoke(dense_query)

display_documents(
    dense_documents,
    title="Dense Retrieval: Vector Search Results",
)

====================================================================================================
Dense Retrieval: Vector Search Results
====================================================================================================

RANK: 1
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-338
----------------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfu

RANK: 2
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 3
Paper page: 35
Section: discussion
Chunk ID: llama2-page-35-chunk-154
----------------------------------------------------------------------------------------------------
this progression is the rise of Llama, recognized for its focus on computational efficiency during inference
(Touvron et al., 2023). A parallel discourse has unfolded around the dynamics of open-source versus closed-
source models. Open-source releases like BLOOM (Scao et al., 2022), OPT(Zhang et al., 2022), and Falcon
(Penedo et al., 2023) have risen to challenge their closed-source counterparts like GPT-3 and Chinchilla.
§§https://ai.meta.com/llama
35

RANK: 4
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

In [69]:
comparison_query = (
    "How did grouped-query attention improve "
    "Llama 2 inference scalability?"
)

sparse_results = bm25_retriever.invoke(comparison_query)
dense_results = dense_retriever.invoke(comparison_query)

display_documents(
    sparse_results,
    title="BM25 Results",
    max_documents=4,
)

display_documents(
    dense_results,
    title="Dense Vector Results",
    max_documents=4,
)

====================================================================================================
BM25 Results
====================================================================================================

RANK: 1
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 2
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 3
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 4
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

====================================================================================================
Dense Vector Results
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 2
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 3
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 4
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

In [71]:
print("SPARSE RESULTS")
for rank, document in enumerate(sparse_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

print("\nDENSE RESULTS")
for rank, document in enumerate(dense_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

SPARSE RESULTS
1 4 llama2-page-4-chunk-12
2 47 llama2-page-47-chunk-217
3 54 llama2-page-54-chunk-240
4 6 llama2-page-6-chunk-18

DENSE RESULTS
1 6 llama2-page-6-chunk-18
2 47 llama2-page-47-chunk-217
3 4 llama2-page-4-chunk-12
4 13 llama2-page-13-chunk-53

In [72]:
bm25_retriever.k = 8

dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 8
    },
)

In [73]:
from langchain_classic.retrievers.ensemble import EnsembleRetriever
hybrid_retriever = EnsembleRetriever(
    retrievers=[
        bm25_retriever,
        dense_retriever,
    ],
    weights=[
        0.5,  # BM25 weight
        0.5,  # Dense-retrieval weight
    ],
)

In [74]:
hybrid_query = (
    "Llama 2 70B grouped-query attention and inference scalability"
)

In [75]:
hybrid_documents = hybrid_retriever.invoke(hybrid_query)

In [76]:
display_documents(
    hybrid_documents,
    title="Hybrid Retrieval: BM25 + Dense + RRF",
    max_documents=6,
)

====================================================================================================
Hybrid Retrieval: BM25 + Dense + RRF
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 2
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 3
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 4
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-216
----------------------------------------------------------------------------------------------------
Table 16 compares the performance of 2k and 4k context pretraining on long-context benchmarks. Both
modelsaretrainedfor150Btokens,keepingthesamearchitectureandhyperparametersasabaseline,varying
only the context length. We observe improvement on SCROLLS (Shaham et al., 2022), where the average
input length is 3.5k, and no performance degradation on SQUAD (Rajpurkar et al., 2018). Table 17 shows
that the longer context model retains strong performance on various general-purpose tasks.
Grouped-Query Attention. A standard practice for autoregressive decoding is to cache the key (K) and
value (V) p

RANK: 5
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-16
----------------------------------------------------------------------------------------------------
We performed a variety of pretraining data investigations so that users can better understand the potential
capabilities and limitations of our models; results can be found in Section 4.1.
2.2 Training Details
We adopt most of the pretraining setting and model architecture fromLlama 1. We use the standard
transformer architecture (Vaswani et al., 2017), apply pre-normalization using RMSNorm (Zhang and
Sennrich, 2019), use the SwiGLU activation function (Shazeer, 2020), and rotary positional embeddings
(RoPE, Su et al. 2022). The primary architectural differences fromLlama 1 include increased c

RANK: 6
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-27
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and ≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B o

                         ┌── BM25 Retriever ─────┐
User query ──────────────┤                       ├── Weighted RRF
                         └── Dense Retriever ────┘
                                                    ↓
                                            Combined ranking

In [77]:
test_query = (
    "How did Meta make Llama 2 70B efficient for large-scale inference?"
)

In [78]:
sparse_results = bm25_retriever.invoke(test_query)
dense_results = dense_retriever.invoke(test_query)
hybrid_results = hybrid_retriever.invoke(test_query)

In [79]:
display_documents(
    sparse_results,
    title="1. Sparse Retrieval",
    max_documents=4,
)

display_documents(
    dense_results,
    title="2. Dense Retrieval",
    max_documents=4,
)

display_documents(
    hybrid_results,
    title="3. Hybrid Retrieval",
    max_documents=4,
)

====================================================================================================
1. Sparse Retrieval
====================================================================================================

RANK: 1
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 2
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 3
Paper page: 51
Section: appendix
Chunk ID: llama2-page-51-chunk-229
----------------------------------------------------------------------------------------------------
Model Size GSM8k MATH
MPT 7B 6.8 3.0
30B 15.2 3.1
Falcon 7B 6.8 2.3
40B 19.6 5.5
Llama 1
7B 11.0 2.9
13B 17.8 3.9
33B 35.6 7.1
65B 50.9 10.6
Llama 2
7B 14.6 2.5
13B 28.7 3.9
34B 42.2 6.24
70B 56.8 13.5
Table 25: Comparison to other open-source models on mathematical reasoning tasks, GSM8k and MATH
(maj1@1 is reported).
Mathematical Reasoning. In Table 25, we report results forLlama 2 and other open-source datasets on the
GSM8k and MATH tasks.
A.3 Additional Details for Fine-tuning
A.3.1 Detailed Statistics of Meta Human Preference Data
Table 26 shows detailed statistics on Meta human preferenc

RANK: 4
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-241
----------------------------------------------------------------------------------------------------
adapted as an efficient technique for long context attention.
A.3.6 How Far Can Model-Based Evaluation Go?
To measure the robustness of our reward model, we collected a test set of prompts for both helpfulness and
safety, and asked annotators to judge quality of the answers based on a 7 point Likert-scale (the higher the
better) using triple reviews. As illustrated in Figure 29 (in Appendix), we observe that our reward models
overallarewellcalibratedwithhumanpreference. Notethatthisenablesustousetherewardasapoint-wise
metric, despite being trained with a Pairwise Ranking Loss.
0.0% 2.0% 4.0% 6

====================================================================================================
2. Dense Retrieval
====================================================================================================

RANK: 1
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-338
----------------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfu

RANK: 2
Paper page: 35
Section: discussion
Chunk ID: llama2-page-35-chunk-154
----------------------------------------------------------------------------------------------------
this progression is the rise of Llama, recognized for its focus on computational efficiency during inference
(Touvron et al., 2023). A parallel discourse has unfolded around the dynamics of open-source versus closed-
source models. Open-source releases like BLOOM (Scao et al., 2022), OPT(Zhang et al., 2022), and Falcon
(Penedo et al., 2023) have risen to challenge their closed-source counterparts like GPT-3 and Chinchilla.
§§https://ai.meta.com/llama
35

RANK: 3
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 4
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-27
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and ≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B o

====================================================================================================
3. Hybrid Retrieval
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 2
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-27
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and ≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B o

RANK: 3
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-28
----------------------------------------------------------------------------------------------------
in Table 4,Llama 2 70B is close to GPT-3.5 (OpenAI, 2023) on MMLU and GSM8K, but there is a significant
gap on coding benchmarks.Llama 2 70B results are on par or better than PaLM (540B) (Chowdhery et al.,
2022) on almost all benchmarks. There is still a large gap in performance betweenLlama 2 70B and GPT-4
and PaLM-2-L.
We also analysed the potential data contamination and share the details in Section A.6.
Benchmark (shots) GPT-3.5 GPT-4 PaLM PaLM-2-L Llama 2
MMLU (5-shot) 70.0 86.4 69.3 78.3 68.9
TriviaQA (1-shot) – – 81.4 86.1 85.0
Natural Questions (1-shot) – – 29.3 37.5 33.0
GSM8K (8-shot

RANK: 4
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

# Query Decomposition

In [83]:
import os
from langchain_groq import ChatGroq

CHAT_MODEL = os.environ.get(
    "GROQ_CHAT_MODEL",
    "openai/gpt-oss-120b",
)

llm = ChatGroq(
    model=CHAT_MODEL,
    temperature=0,
)

print("Chat model:", CHAT_MODEL)

Chat model: openai/gpt-oss-120b

# manual query rewriting code

In [86]:
query_rewriting_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You rewrite conversational questions into clear,
standalone search queries.

Rules:
1. Do not answer the question.
2. Preserve important entities, dates, and technical terms.
3. Resolve pronouns using the conversation history.
4. Return only one rewritten query.
""",
        ),
        (
            "human",
            """
Conversation history:
{chat_history}

Current query:
{query}
""",
        ),
    ]
)

In [87]:
query_rewriting_chain = (query_rewriting_prompt| llm | StrOutputParser())

In [88]:
chat_history = """
User: How was Llama 2-Chat initially fine-tuned?
Assistant: It first underwent supervised fine-tuning.
"""

In [89]:
original_query = "What did Meta do after that?"

In [90]:
rewritten_query = query_rewriting_chain.invoke(
    {
        "chat_history": chat_history,
        "query": original_query,
    }
).strip()

In [91]:
print("Original query:")
print(original_query)

print("\nRewritten query:")
print(rewritten_query)

Original query:
What did Meta do after that?

Rewritten query:
Meta subsequent training steps for Llama 2‑Chat after supervised fine‑tuning

In [92]:
rewritten_query_documents = hybrid_retriever.invoke(
    rewritten_query
)

In [93]:
display_documents(
    rewritten_query_documents,
    title="Documents Retrieved Using the Rewritten Query",
    max_documents=5,
)

====================================================================================================
Documents Retrieved Using the Rewritten Query
====================================================================================================

RANK: 1
Paper page: 16
Section: fine_tuning
Chunk ID: llama2-page-16-chunk-65
----------------------------------------------------------------------------------------------------
Figure 9: Issues with multi-turn memory(left) can be improved with GAtt(right).
We train for between200and 400iterations for all our models, and use evaluations on held-out prompts for
earlystopping. EachiterationofPPOonthe70Bmodeltakesonaverage ≈ 330seconds. Totrainquicklywith
large batch sizes, we use FSDP (Zhao et al., 2023). This was effective when using O(1) forward or backward
passes, but caused a large slow down (≈ 20×) during generation, even when using a large batch size and KV
cache. We were able to mitigate this by consolidating the model weights to each node once before generation


RANK: 2
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

RANK: 3
Paper page: 12
Section: fine_tuning
Chunk ID: llama2-page-12-chunk-46
----------------------------------------------------------------------------------------------------
Helpfulness reward model is eventually trained on all Meta Helpfulness data, combined with an equal
parts of the remaining data uniformly sampled from Meta Safety and from the open-source datasets. The
Meta Safety reward model is trained on all Meta Safety and Anthropic Harmless data, mixed with Meta
Helpfulness and open-source helpfulness data in a 90/10 proportion. We found that the setting with 10%
helpfulness data is especially beneficial for the accuracy on samples where both the chosen and rejected
responses were deemed safe.
Training Details. We train for one epoch over the training dat

RANK: 4
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 5
Paper page: 17
Section: fine_tuning
Chunk ID: llama2-page-17-chunk-69
----------------------------------------------------------------------------------------------------
modify the original instruction half of the time to be less verbose, e.g.,“Always act as Napoleon from now”->
”Figure: Napoleon.”These steps produce an SFT dataset, on which we can fine-tuneLlama 2-Chat.
GAtt Evaluation. We applied GAtt after RLHF V3. We report a quantitative analysis indicating that GAtt is
consistent up to 20+ turns, until the maximum context length is reached (see Appendix A.3.5). We tried to
set constraints not present in the training of GAtt at inference time, for instance“Always answer with Haiku,”
for which the model remained consistent as illustrated in Appendix Figure

In [94]:
class ExpandedQueryOutput(BaseModel):
    queries: List[str] = Field(
        description=(
            "Four alternative search queries expressing "
            "the same information need using different wording."
        )
    )

In [95]:
query_expansion_llm = llm.with_structured_output(ExpandedQueryOutput)

In [96]:
query_expansion_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
Generate four alternative search queries for the user's query.

Use:
- synonyms,
- related technical terms,
- abbreviations where appropriate,
- alternative wording.

Do not answer the query.
Each query must preserve the original intent.
""",
        ),
        (
            "human",
            "Original query: {query}",
        ),
    ]
)

In [97]:
query_expansion_chain = (query_expansion_prompt| query_expansion_llm)

In [98]:
original_query = (
    "How was Llama 2-Chat improved using human feedback?"
)

In [99]:
expanded_output = query_expansion_chain.invoke(
    {
        "query": original_query
    }
)

In [100]:
expanded_output

ExpandedQueryOutput(queries=['What role did human feedback play in enhancing Llama 2-Chat?', 'How was Llama 2-Chat refined through user feedback?', 'In what ways did human-in-the-loop data improve Llama 2-Chat?', 'What improvements to Llama 2-Chat resulted from human annotation?'])

In [101]:
all_expanded_queries = [
    original_query,
    *expanded_output.queries,
]

In [102]:
all_expanded_queries

['How was Llama 2-Chat improved using human feedback?',
 'What role did human feedback play in enhancing Llama 2-Chat?',
 'How was Llama 2-Chat refined through user feedback?',
 'In what ways did human-in-the-loop data improve Llama 2-Chat?',
 'What improvements to Llama 2-Chat resulted from human annotation?']

In [103]:
print("Generated search queries:\n")

for number, query in enumerate(
    all_expanded_queries,
    start=1,
):
    print(f"{number}. {query}")

Generated search queries:

1. How was Llama 2-Chat improved using human feedback?
2. What role did human feedback play in enhancing Llama 2-Chat?
3. How was Llama 2-Chat refined through user feedback?
4. In what ways did human-in-the-loop data improve Llama 2-Chat?
5. What improvements to Llama 2-Chat resulted from human annotation?

In [104]:
expanded_query_documents = []

for query in all_expanded_queries:
    current_documents = dense_retriever.invoke(query)
    expanded_query_documents.extend(current_documents)

expanded_query_documents = deduplicate_documents(
    expanded_query_documents
)

display_documents(
    expanded_query_documents,
    title="Query Expansion: Combined Unique Documents",
    max_documents=10,
)

====================================================================================================
Query Expansion: Combined Unique Documents
====================================================================================================

RANK: 1
Paper page: 18
Section: fine_tuning
Chunk ID: llama2-page-18-chunk-77
----------------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for ju

RANK: 2
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 3
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-29
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 4
Paper page: 19
Section: fine_tuning
Chunk ID: llama2-page-19-chunk-79
----------------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generatio

RANK: 5
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 6
Paper page: 10
Section: fine_tuning
Chunk ID: llama2-page-10-chunk-38
----------------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latest

RANK: 7
Paper page: 11
Section: fine_tuning
Chunk ID: llama2-page-11-chunk-45
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 8
Paper page: 58
Section: appendix
Chunk ID: llama2-page-58-chunk-253
----------------------------------------------------------------------------------------------------
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in either case.
A.4 Additional Details for Safety
A.4.1 Tension between Safety and Helpfulness in Reward Mo

RANK: 9
Paper page: 58
Section: appendix
Chunk ID: llama2-page-58-chunk-252
----------------------------------------------------------------------------------------------------
Figure 31:Win rate ofLlama 2-Chat versus ChatGPT analyzed by number of turns (Left) in the prompt and
word count (Right) for the prompt and generation combined. For the word count plot, we report the win rate
for each quintile. The maximum total word count (prompt and generation) is 2432. We do not see any trends
in win rate with either word count or turn count.
Additional Results. To understand the impact of system prompt on ChatGPT generations, we ran another
human evaluation without any system prompt for ChatGPT. As shown in Figure 30,Llama 2-Chat win rate
increases from 36% to 44%. Additio

RANK: 10
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-13
----------------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), a

# in built langchain function to perform the multi query rewriting

In [109]:
from langchain_classic.retrievers.multi_query import (
    MultiQueryRetriever,
)

In [110]:
multi_query_retriever = MultiQueryRetriever.from_llm(
    retriever=dense_retriever,
    llm=llm,
    include_original=True,
)

In [111]:
multi_query_documents = multi_query_retriever.invoke(
    "How did human feedback improve Llama 2-Chat?"
)

In [112]:
display_documents(
    multi_query_documents,
    title="Built-in MultiQueryRetriever Results",
    max_documents=10,
)

====================================================================================================
Built-in MultiQueryRetriever Results
====================================================================================================

RANK: 1
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 2
Paper page: 18
Section: fine_tuning
Chunk ID: llama2-page-18-chunk-77
----------------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for ju

RANK: 3
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-29
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 4
Paper page: 11
Section: fine_tuning
Chunk ID: llama2-page-11-chunk-45
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 5
Paper page: 19
Section: fine_tuning
Chunk ID: llama2-page-19-chunk-79
----------------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generatio

RANK: 6
Paper page: 58
Section: appendix
Chunk ID: llama2-page-58-chunk-253
----------------------------------------------------------------------------------------------------
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in either case.
A.4 Additional Details for Safety
A.4.1 Tension between Safety and Helpfulness in Reward Mo

RANK: 7
Paper page: 58
Section: appendix
Chunk ID: llama2-page-58-chunk-252
----------------------------------------------------------------------------------------------------
Figure 31:Win rate ofLlama 2-Chat versus ChatGPT analyzed by number of turns (Left) in the prompt and
word count (Right) for the prompt and generation combined. For the word count plot, we report the win rate
for each quintile. The maximum total word count (prompt and generation) is 2432. We do not see any trends
in win rate with either word count or turn count.
Additional Results. To understand the impact of system prompt on ChatGPT generations, we ran another
human evaluation without any system prompt for ChatGPT. As shown in Figure 30,Llama 2-Chat win rate
increases from 36% to 44%. Additio

RANK: 8
Paper page: 10
Section: fine_tuning
Chunk ID: llama2-page-10-chunk-38
----------------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latest

RANK: 9
Paper page: 56
Section: appendix
Chunk ID: llama2-page-56-chunk-244
----------------------------------------------------------------------------------------------------
A.3.7 Human Evaluation
PromptsandGenerations. Tocomparethemodels,wecollectadiversesetofover4000singleandmultiturn
prompts. We manually collected single turn prompts spanning the following categories: factual questions,
writing and content creation, language assistance, recommendations, and dialogue. For multi-turn prompts,
annotators interacted with another model to generate a set of multi-turn prompts. To help ensure fairness,
we asked annotators to collect multi-turn prompts by using four different interaction methods: (a) ChatGPT
as the interaction model, (b)Llama 2-Chat as the interaction

RANK: 10
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-215
----------------------------------------------------------------------------------------------------
• Armand Joulin, Edouard Grave, Guillaume Lample, and Timothee Lacroix, members of the original
Llama team who helped get this work started.
• Drew Hamlin, Chantal Mora, and Aran Mun, who gave us some design input on the figures in the
paper.
• Vijai Mohan for the discussions about RLHF that inspired our Figure 20, and his contribution to the
internal demo.
• Earlyreviewersofthispaper,whohelpedusimproveitsquality,includingMikeLewis,JoellePineau,
Laurens van der Maaten, Jason Weston, and Omer Levy.
A.2 Additional Details for Pretraining
A.2.1 Architecture Changes Compared toLlama 1
Context Leng

In [113]:
class DecomposedQueryOutput(BaseModel):
    sub_queries: List[str] = Field(
        description=(
            "Independent and atomic search queries required "
            "to answer the complete user question."
        )
    )

In [114]:
query_decomposition_llm = llm.with_structured_output(
    DecomposedQueryOutput
)

In [115]:
query_decomposition_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
Break the user's complex question into independent,
atomic search queries.

Rules:
1. Do not answer the question.
2. Generate only sub-queries needed to answer it.
3. Each sub-query must be understandable independently.
4. Preserve named entities, model names, and dates.
5. Generate between two and five sub-queries.
""",
        ),
        (
            "human",
            "Complex query: {query}",
        ),
    ]
)

In [116]:
query_decomposition_chain = (
    query_decomposition_prompt
    | query_decomposition_llm
)

In [117]:
complex_query = """
Compare Llama 2 pretraining with Llama 2-Chat fine-tuning,
and explain how Meta improved model safety.
"""

In [118]:
decomposed_output = query_decomposition_chain.invoke(
    {
        "query": complex_query
    }
)

In [119]:
sub_queries = decomposed_output.sub_queries

In [72]:
print("Original complex query:")
print(complex_query)

print("\nGenerated sub-queries:")

for number, query in enumerate(sub_queries, start=1):
    print(f"{number}. {query}")

Original complex query:

Compare Llama 2 pretraining with Llama 2-Chat fine-tuning,
and explain how Meta improved model safety.


Generated sub-queries:
1. What is the pretraining process of Llama 2?
2. What is the fine-tuning process of Llama 2-Chat?
3. How does Meta improve model safety in Llama 2 and Llama 2-Chat?

In [120]:
decomposition_results = {}

for sub_query in sub_queries:
    decomposition_results[sub_query] = hybrid_retriever.invoke(
        sub_query
    )

In [121]:
for sub_query, documents in decomposition_results.items():
    display_documents(
        documents,
        title=f"Sub-query: {sub_query}",
        max_documents=4,
    )

====================================================================================================
Sub-query: What are the data sources, architecture, and training objectives used in the pretraining of Meta's Llama 2 model?
====================================================================================================

RANK: 1
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-340
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2was pretrained on 2 trillion tokens of data from publicly

RANK: 2
Paper page: 7
Section: pretraining
Chunk ID: llama2-page-7-chunk-23
----------------------------------------------------------------------------------------------------
We estimate the total emissions for training to be539 tCO2eq, of which 100% were directly offset by Meta’s
sustainability program.∗∗ Our open release strategy also means that these pretraining costs will not need to
be incurred by other companies, saving more global resources.
2.3 Llama 2 Pretrained Model Evaluation
In this section, we report the results for theLlama 1 and Llama 2 base models, MosaicML Pretrained
Transformer(MPT) ††models,andFalcon(Almazroueietal.,2023)modelsonstandardacademicbenchmarks.
For all the evaluations, we use our internal evaluations library. We reproduce results for

RANK: 3
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-15
----------------------------------------------------------------------------------------------------
Specifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total
tokens,doubledthecontextlength,andusedgrouped-queryattention(GQA)toimproveinferencescalability
for our larger models. Table 1 compares the attributes of the newLlama 2 models with theLlama 1 models.
2.1 Pretraining Data
Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals.

RANK: 4
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-338
----------------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfu

====================================================================================================
Sub-query: What fine-tuning methods, datasets, and objectives were employed for Meta's Llama 2-Chat model?
====================================================================================================

RANK: 1
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

RANK: 2
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-29
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 3
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-340
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2was pretrained on 2 trillion tokens of data from publicly

RANK: 4
Paper page: 36
Section: conclusion
Chunk ID: llama2-page-36-chunk-160
----------------------------------------------------------------------------------------------------
of 7 billion to 70 billion parameters. These models have demonstrated their competitiveness with existing
open-source chat models, as well as competency that is equivalent to some proprietary models on evaluation
sets we examined, although they still lag behind other models like GPT-4. We meticulously elaborated on the
methodsandtechniquesappliedinachievingourmodels,withaheavyemphasisontheiralignmentwiththe
principlesofhelpfulnessandsafety. Tocontributemoresignificantlytosocietyandfosterthepaceofresearch,
we have responsibly opened access toLlama 2 and Llama 2-Chat. As part of our ongoing comm

====================================================================================================
Sub-query: What are the key differences between Llama 2 pretraining and Llama 2-Chat fine-tuning in terms of data, objectives, and performance metrics?
====================================================================================================

RANK: 1
Paper page: 31
Section: safety
Chunk ID: llama2-page-31-chunk-135
----------------------------------------------------------------------------------------------------
manceissimilaracrosscategories, Llama 2-Chathasrelativelymoreviolationsunderthe unqualifiedadvice
category (although still low in an absolute sense), for various reasons, including lack of an appropriate
disclaimer (e.g.,“I am not a professional”) at times. For the other two categories,Llama 2-Chat achieves
comparable or lower violation percentage consistently regardless of model sizes.
Truthfulness, Toxicity, and Bias.In Table 14, fine-tunedLlama 2-Chat shows great improvement over
the pretrainedLlama 2 in terms of truthfulness (50.18 → 64.14 for 70B) and toxicity (24.60 → 0.01 for 70B).
The

RANK: 2
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-29
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 3
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-13
----------------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), a

RANK: 4
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

====================================================================================================
Sub-query: What safety techniques and mitigations did Meta introduce to improve the safety of Llama 2 and Llama 2-Chat models?
====================================================================================================

RANK: 1
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-10
----------------------------------------------------------------------------------------------------
continue to improve the safety of those models, paving the way for more responsible development of LLMs.
We also share novel observations we made during the development ofLlama 2 and Llama 2-Chat, such as
the emergence of tool usage and temporal organization of knowledge.
3

RANK: 2
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 3
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-13
----------------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), a

RANK: 4
Paper page: 20
Section: safety
Chunk ID: llama2-page-20-chunk-84
----------------------------------------------------------------------------------------------------
light on root causes of potential downstream issues, such as potential biases. This can inform what, if any,
downstream mitigations to consider, and help guide appropriate model use. In this section, we analyze the
pretraining data for distributions of languages, demographic representations, and toxicity. We also present
the results of testing the pretrained models on existing safety benchmarks.
Steps Taken to Pretrain Responsibly.We followed Meta’s standard privacy and legal review processes for
each dataset used in training. We did not use any Meta user data in training. We excluded data fro

In [122]:
all_decomposition_documents = []

for documents in decomposition_results.values():
    all_decomposition_documents.extend(documents)

all_decomposition_documents = deduplicate_documents(
    all_decomposition_documents
)

display_documents(
    all_decomposition_documents,
    title="Combined Evidence from All Sub-Queries",
    max_documents=12,
)

====================================================================================================
Combined Evidence from All Sub-Queries
====================================================================================================

RANK: 1
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-340
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2was pretrained on 2 trillion tokens of data from publicly

RANK: 2
Paper page: 7
Section: pretraining
Chunk ID: llama2-page-7-chunk-23
----------------------------------------------------------------------------------------------------
We estimate the total emissions for training to be539 tCO2eq, of which 100% were directly offset by Meta’s
sustainability program.∗∗ Our open release strategy also means that these pretraining costs will not need to
be incurred by other companies, saving more global resources.
2.3 Llama 2 Pretrained Model Evaluation
In this section, we report the results for theLlama 1 and Llama 2 base models, MosaicML Pretrained
Transformer(MPT) ††models,andFalcon(Almazroueietal.,2023)modelsonstandardacademicbenchmarks.
For all the evaluations, we use our internal evaluations library. We reproduce results for

RANK: 3
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-15
----------------------------------------------------------------------------------------------------
Specifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total
tokens,doubledthecontextlength,andusedgrouped-queryattention(GQA)toimproveinferencescalability
for our larger models. Table 1 compares the attributes of the newLlama 2 models with theLlama 1 models.
2.1 Pretraining Data
Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals.

RANK: 4
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-338
----------------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfu

RANK: 5
Paper page: 24
Section: safety
Chunk ID: llama2-page-24-chunk-108
----------------------------------------------------------------------------------------------------
previous studies (Bai et al., 2022a). To better understand how the addition of safety training data affects
general model performance, especially helpfulness, we investigate the trends in safety data scaling by
adjustingtheamount ofsafety dataused intheRLHF stage. In this ablationexperiment, we keeptheamount
of helpfulness training data unchanged (∼0.9M samples) and gradually increase the amount of safety data
used in model tuning, ranging from 0% to 100% (∼0.1M samples). For the specific training data mix recipe,
we follow the procedure described in Section 3.1 and fine-tuneLlama 2 pretrained

RANK: 6
Paper page: 11
Section: fine_tuning
Chunk ID: llama2-page-11-chunk-45
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 7
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 8
Paper page: 20
Section: safety
Chunk ID: llama2-page-20-chunk-86
----------------------------------------------------------------------------------------------------
representing “people” are often used in more similar contexts to words representing“men”than to words
representing“women,”and Ganeshet al.(2023) demonstrates that amodel’sperformance onfairness metrics
can be highly dependent on how the model trains on data representing underrepresented demographic
groups. Within our English-language training corpus, we computed the frequencies of the most common
English pronouns in Table 9a. We observe thatHe pronouns are generally overrepresented in documents
compared toShe pronouns, echoing similar frequency differences observed in pronominal usage for simi

RANK: 9
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 10
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-341
----------------------------------------------------------------------------------------------------
nor the fine-tuning datasets include Meta user data.
Data Freshness The pretraining data has a cutoff of September 2022, but some tuning data is
more recent, up to July 2023.
Evaluation Results
See evaluations for pretraining (Section 2); fine-tuning (Section 3); and safety (Section 4).
Ethical Considerations and Limitations(Section 5.2)
Llama 2is a new technology that carries risks with use. Testing conducted to date has been in
English, and has not covered, nor could it cover all scenarios. For these reasons, as with all LLMs,
Llama 2’s potential outputs cannot be predicted in advance, and t

RANK: 11
Paper page: 7
Section: pretraining
Chunk ID: llama2-page-7-chunk-21
----------------------------------------------------------------------------------------------------
Time
(GPU hours)
Power
Consumption (W)
Carbon Emitted
(tCO2eq)
Llama 2
7B 184320 400 31.22
13B 368640 400 62.44
34B 1038336 350 153.90
70B 1720320 400 291.42
Total 3311616 539.00
Table 2:CO2 emissions during pretraining.Time: total GPU time required for training each model. Power
Consumption: peak power capacity per GPU device for the GPUs used adjusted for power usage efficiency.
100%oftheemissionsaredirectlyoffsetbyMeta’ssustainabilityprogram,andbecauseweareopenlyreleasing
these models, the pretraining costs do not need to be incurred by others.
can scale almost as well as expensive Infiniba

RANK: 12
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

Complex query
      ↓
Atomic sub-queries
      ↓
Retrieve for every sub-query
      ↓
Merge evidence
      ↓
Remove duplicates

## HyDE (Hypothetical Document Embeddings)

HyDE asks an LLM to write a plausible passage that could answer the query. The hypothetical passage is embedded and used for dense retrieval instead of embedding the short user query directly. The generated text is only a search aid; the final answer must still be grounded in retrieved source documents.

In [123]:
from typing import Any

from langchain_core.retrievers import BaseRetriever


class HyDERetriever(BaseRetriever):
    """Generate a hypothetical passage and retrieve real documents with it."""

    hypothesis_chain: Any
    vector_retriever: Any
    last_hypothetical_document: str = ""

    def _get_relevant_documents(
        self,
        query: str,
        *,
        run_manager,
    ):
        hypothetical_document = self.hypothesis_chain.invoke(
            {"query": query}
        ).strip()

        self.last_hypothetical_document = hypothetical_document

        return self.vector_retriever.invoke(
            hypothetical_document,
            config={
                "callbacks": run_manager.get_child(),
            },
        )

In [124]:
hyde_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
Write a concise research-paper passage that would directly answer the user's question.
Use technical terminology and named entities likely to appear in the source document.
Do not mention that the passage is hypothetical.
Do not add citations, headings, or commentary.
Return only the passage.
""",
        ),
        ("human", "Question: {query}"),
    ]
)

hyde_hypothesis_chain = (
    hyde_prompt
    | llm
    | StrOutputParser()
)

hyde_dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5},
)

hyde_retriever = HyDERetriever(
    hypothesis_chain=hyde_hypothesis_chain,
    vector_retriever=hyde_dense_retriever,
)

In [125]:
hyde_query = (
    "How did Meta use human feedback to improve the helpfulness "
    "and safety of Llama 2-Chat?"
)

hyde_documents = hyde_retriever.invoke(hyde_query)

print("Original query:")
print(hyde_query)

print("\nHypothetical document used for retrieval:")
print(hyde_retriever.last_hypothetical_document)

display_documents(
    hyde_documents,
    title="HyDE Retrieval Results",
    max_documents=5,
)

Original query:
How did Meta use human feedback to improve the helpfulness and safety of Llama 2-Chat?

Hypothetical document used for retrieval:
Meta improved Llama 2‑Chat’s helpfulness and safety by integrating a multi‑stage human‑feedback loop into its fine‑tuning pipeline. First, a curated set of high‑quality instruction–response pairs was generated through supervised fine‑tuning (SFT) using expert annotators who rated responses for relevance, factuality, and tone. These annotations were then used to train a reward model that predicts human preference scores. The reward model guided a reinforcement learning from human feedback (RLHF) stage, where policy gradients adjusted the language model to maximize predicted preference while respecting safety constraints. Parallel to RLHF, a dedicated safety‑fine‑tuning phase employed red‑team annotations that labeled toxic, biased, or disallowed content; a binary safety classifier was trained on this data and incorporated as a penalty term during RLHF optimization. Iterative cycles of red‑team testing, annotator review, and model re‑training refined both the reward model and the safety classifier, resulting in a final Llama 2‑Chat checkpoint that demonstrates higher helpfulness scores on benchmark instruction sets and reduced incidence of unsafe generations in adversarial evaluations.

====================================================================================================
HyDE Retrieval Results
====================================================================================================

RANK: 1
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 2
Paper page: 24
Section: safety
Chunk ID: llama2-page-24-chunk-106
----------------------------------------------------------------------------------------------------
preference data to train a safety reward model (see Section 3.2.2), and also reuse the adversarial prompts to
sample from the model during the RLHF stage.
Better Long-Tail Safety Robustness without Hurting HelpfulnessSafety is inherently a long-tail problem,
where the challenge comes from a small number of very specific cases. We investigate the impact of Safety
RLHFbytakingtwointermediate Llama 2-Chatcheckpoints—onewithoutadversarialpromptsintheRLHF
stage and one with them—and score their responses on our test sets using our safety and helpfulness reward
models. In Figure 14, we plot the scor

RANK: 3
Paper page: 36
Section: conclusion
Chunk ID: llama2-page-36-chunk-157
----------------------------------------------------------------------------------------------------
In this paradigm, models are fine-tuned based on feedback from human users, thus iteratively aligning the
models’ responses more closely with human expectations and preferences.
Ouyang et al. (2022) demonstrates that a combination of instruction fine-tuning and RLHF can help fix
issues with factuality, toxicity, and helpfulness that cannot be remedied by simply scaling up LLMs. Bai
et al. (2022b) partially automates this fine-tuning-plus-RLHF approach by replacing the human-labeled
fine-tuning data with the model’s own self-critiques and revisions, and by replacing human raters with a
model wh

RANK: 4
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-29
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 5
Paper page: 10
Section: fine_tuning
Chunk ID: llama2-page-10-chunk-40
----------------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we trai

User query
     ↓
LLM-generated hypothetical document
     ↓
Embed the hypothetical document
     ↓
Dense vector search
     ↓
Real source documents

## HyDE with LangChain's built-in helper

`HypotheticalDocumentEmbedder` is an embeddings wrapper, not a complete retriever. For a query, it generates a hypothetical document with the LLM and embeds that generated text. Chroma then uses the resulting vector to search the collection of real PDF chunks.

In [1]:
try:
    # LangChain v1: legacy chains live in langchain-classic.
    from langchain_classic.chains.hyde.base import (
        HypotheticalDocumentEmbedder,
    )
except ImportError:
    # Compatibility fallback for older LangChain versions.
    from langchain.chains.hyde.base import (
        HypotheticalDocumentEmbedder,
    )

d:\complete_content_new\Full-Stack-GenAI-Bootcamp-1.0\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
built_in_hyde_embeddings = (
    HypotheticalDocumentEmbedder.from_llm(
        llm=llm,
        base_embeddings=embeddings,
        prompt_key="web_search",
    )
)

# Reuse the existing collection. Real PDF chunks remain embedded with
# `embeddings`; HyDE is used only to transform query embeddings.
built_in_hyde_vector_store = Chroma(
    collection_name="llama2_retriever_demo",
    embedding_function=built_in_hyde_embeddings,
    persist_directory=str(PERSIST_DIRECTORY),
)

built_in_hyde_retriever = (
    built_in_hyde_vector_store.as_retriever(
        search_type="similarity",
        search_kwargs={"k": 5},
    )
)

NameError: name 'llm' is not defined

In [ ]:
built_in_hyde_query = (
    "How did Meta use human feedback to improve the helpfulness "
    "and safety of Llama 2-Chat?"
)

built_in_hyde_documents = (
    built_in_hyde_retriever.invoke(
        built_in_hyde_query
    )
)

display_documents(
    built_in_hyde_documents,
    title="Built-in LangChain HyDE Results",
    max_documents=5,
)

> **Note:** Do not use `built_in_hyde_embeddings` when initially indexing the PDF chunks. Index real documents with the normal `OpenAIEmbeddings` object, then use the HyDE wrapper only when loading the collection for retrieval.

In [76]:
candidate_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 20
    },
)

Vector search
     ↓
Top 20 candidates

In [77]:
cross_encoder = HuggingFaceCrossEncoder(
    model_name="cross-encoder/ms-marco-MiniLM-L6-v2",
    model_kwargs={
        "device": "cpu"
    },
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
d:\complete_content_new\Full-Stack-GenAI-Bootcamp-1.0\env\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Sunny\.cache\huggingface\hub\models--cross-encoder--ms-marco-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 13097.84it/s]

In [78]:
cross_encoder_reranker = CrossEncoderReranker(
    model=cross_encoder,
    top_n=5,
)

In [79]:
reranking_retriever = ContextualCompressionRetriever(
    base_retriever=candidate_retriever,
    base_compressor=cross_encoder_reranker,
)

In [80]:
reranking_query = (
    "How did Meta collect and use human preference data to train Llama 2-Chat?"
)

In [81]:
initial_candidates = candidate_retriever.invoke(
    reranking_query
)

In [82]:
initial_candidates

[Document(id='577892fb-3838-4c4d-9978-4488765bf837', metadata={'producer': 'pdfTeX-1.40.25', 'year': 2023, 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'creationdate': '2023-07-20T00:30:36+00:00', 'paper_page': 10, 'paper': 'Llama 2', 'title': '', 'page': 9, 'keywords': '', 'section': 'fine_tuning', 'chunk_id': 'llama2-page-10-chunk-38', 'author': '', 'document_type': 'research_paper', 'moddate': '2023-07-20T00:30:36+00:00', 'total_pages': 77, 'subject': '', 'creator': 'LaTeX with hyperref', 'start_index': 2384, 'page_label': '10', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'trapped': '/False', 'organization': 'Meta', 'access_level': 'public'}, page_content='can be found in Section 4.2.1.\nHuman annotations were collected in batches on a weekly basis. As we collected more preference data, our\nreward models improved, and we were able to train progressively better versions forLlama 2-Chat (see\nthe results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.\nSince reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from\nhyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to\ngather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model\non-distribution and maintain an accurate reward for the latest model.\nIn Table 6, we report the statistics of reward modeling data that we collected over time, and present them\nagainst multiple open-source preference datasets including Anthropic Helpful and Harmless (Bai et al.,'),
 Document(id='e78f003f-9087-47c6-a655-3f0ea3db90b0', metadata={'creationdate': '2023-07-20T00:30:36+00:00', 'chunk_id': 'llama2-page-5-chunk-14', 'total_pages': 77, 'creator': 'LaTeX with hyperref', 'access_level': 'public', 'organization': 'Meta', 'paper': 'Llama 2', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'section': 'pretraining', 'year': 2023, 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'author': '', 'moddate': '2023-07-20T00:30:36+00:00', 'document_type': 'research_paper', 'page_label': '5', 'trapped': '/False', 'paper_page': 5, 'keywords': '', 'page': 4, 'title': '', 'start_index': 0, 'subject': '', 'producer': 'pdfTeX-1.40.25'}, page_content='Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly\navailable online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application\nof supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning\nwith Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy\nOptimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain\nparallel with model enhancements is crucial to ensure the reward models remain within distribution.\n2 Pretraining\nTocreatethenewfamilyof Llama 2models,webeganwiththepretrainingapproachdescribedinTouvronetal.\n(2023), using an optimized auto-regressive transformer, but made several changes to improve performance.\nSpecifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total'),
 Document(id='82866a87-5d44-41ab-88f2-7e345bd98799', metadata={'author': '', 'creator': 'LaTeX with hyperref', 'section': 'fine_tuning', 'paper': 'Llama 2', 'page': 10, 'organization': 'Meta', 'page_label': '11', 'creationdate': '2023-07-20T00:30:36+00:00', 'title': '', 'paper_page': 11, 'access_level': 'public', 'year': 2023, 'start_index': 3419, 'chunk_id': 'llama2-page-11-chunk-45', 'moddate': '2023-07-20T00:30:36+00:00', 'keywords': '', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'trapped': '/False', 'subject': '', 'document_type': 'research_paper', 'producer': 'pdfTeX-1.40.25', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5'}, page_content='this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than\nany modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source\npreference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better\ngeneralization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of\nsome weaknesses of our reward, and so artificially inflating the score despite performing less well.\nWith training data available from different sources, we experimented with different mixing recipes for both\nHelpfulness and Safety reward models to ascertain the best settings. After extensive experimentation, the\n11'),
 Document(id='dfa4620d-18a2-4f8f-959e-c7f01c1fbbb2', metadata={'year': 2023, 'title': '', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'page': 17, 'organization': 'Meta', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'access_level': 'public', 'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'paper': 'Llama 2', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'start_index': 1558, 'section': 'fine_tuning', 'paper_page': 18, 'chunk_id': 'llama2-page-18-chunk-77', 'keywords': '', 'page_label': '18', 'moddate': '2023-07-20T00:30:36+00:00', 'total_pages': 77, 'document_type': 'research_paper', 'trapped': '/False', 'subject': ''}, page_content='biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results\nusingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs\nappeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of\nLlama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.\nThe prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.\n3.4.2 Human Evaluation\nHuman evaluation is often considered the gold standard for judging models for natural language generation,\nincluding dialogue models. To evaluate the quality of major model versions, we asked human evaluators to\nrate them on helpfulness and safety. We compare theLlama 2-Chat models to open-source models (Falcon,\nMPT MosaicML NLP Team et al. (2023), Vicuna Chiang et al. (2023), as well as closed-source models (Chat-'),
 Document(id='eebf4d86-d511-4452-9b14-2e4990f9fb39', metadata={'moddate': '2023-07-20T00:30:36+00:00', 'title': '', 'paper_page': 51, 'subject': '', 'producer': 'pdfTeX-1.40.25', 'page': 50, 'page_label': '51', 'section': 'appendix', 'keywords': '', 'creationdate': '2023-07-20T00:30:36+00:00', 'creator': 'LaTeX with hyperref', 'document_type': 'research_paper', 'organization': 'Meta', 'total_pages': 77, 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'access_level': 'public', 'paper': 'Llama 2', 'year': 2023, 'start_index': 868, 'chunk_id': 'llama2-page-51-chunk-230', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'author': ''}, page_content='time and the annotators also become more familiar with the tasks and thus have better work efficiency. We\nalso intentionally collect more multi-turn samples to increase the complexity of RLHF data and thus the\naverage number of tokens per sample also increase accordingly over batches.\nIn Figure 25, we plot out the preference rating change over batches. It can be clearly seen that the share\nof samples with similar responses (e.g.,negligibly better or unsure) increase dramatically over time while\nthose with stronger preference (e.g.,significantly better) drop in the meantime. This reflects the nature of our\niterative model update and preference data annotation procedure - with better-performingLlama 2-Chat\nmodels used for response sampling over time, it becomes challenging for annotators to select a better one\nfrom two equally high-quality responses.\nA.3.2 Curriculum Strategy for Meta Human Preference Data'),
 Document(id='1767dbfa-8296-42eb-9aa3-239c40ef6027', metadata={'trapped': '/False', 'moddate': '2023-07-20T00:30:36+00:00', 'organization': 'Meta', 'paper': 'Llama 2', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'chunk_id': 'llama2-page-13-chunk-53', 'author': '', 'title': '', 'section': 'fine_tuning', 'paper_page': 13, 'creator': 'LaTeX with hyperref', 'producer': 'pdfTeX-1.40.25', 'total_pages': 77, 'year': 2023, 'access_level': 'public', 'subject': '', 'page_label': '13', 'document_type': 'research_paper', 'creationdate': '2023-07-20T00:30:36+00:00', 'start_index': 1687, 'keywords': '', 'page': 12, 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5'}, page_content='mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher\non more distinct responses than similar pairs.\nScaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-\ntuning different model sizes on an increasing amount of the reward model data collected each week (see the\ndetailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger\nmodels obtain higher performance for a similar volume of data. More importantly, the scaling performance\nhas not yet plateaued given the existing volume of data annotation used for training, a signal that there is\nroom for more improvement with more annotations. We note that reward model accuracy is one of the most\nimportant proxies for the final performance ofLlama 2-Chat. While best practices for comprehensively\nevaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.'),
 Document(id='20e348be-39ff-4d6b-a6fa-cd987dbe2a0f', metadata={'producer': 'pdfTeX-1.40.25', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'moddate': '2023-07-20T00:30:36+00:00', 'creationdate': '2023-07-20T00:30:36+00:00', 'creator': 'LaTeX with hyperref', 'document_type': 'research_paper', 'section': 'appendix', 'page': 76, 'author': '', 'subject': '', 'chunk_id': 'llama2-page-77-chunk-340', 'title': '', 'trapped': '/False', 'keywords': '', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'organization': 'Meta', 'total_pages': 77, 'paper_page': 77, 'paper': 'Llama 2', 'start_index': 1669, 'year': 2023, 'page_label': '77', 'access_level': 'public'}, page_content='Llama 2.\nHardware and Software(Section 2.2)\nTraining Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-\ntion clusters for pretraining. Fine-tuning, annotation, and evaluation were also\nperformed on third-party cloud compute.\nCarbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware\nof type A100-80GB (TDP of 350-400W). Estimated total emissions were 539\ntCO2eq, 100% of which were offset by Meta’s sustainability program.\nTraining Data(Sections 2.1 and 3)\nOverview Llama 2was pretrained on 2 trillion tokens of data from publicly available\nsources. The fine-tuning data includes publicly available instruction datasets, as\nwellasoveronemillionnewhuman-annotatedexamples. Neitherthepretraining\nnor the fine-tuning datasets include Meta user data.\nData Freshness The pretraining data has a cutoff of September 2022, but some tuning data is\nmore recent, up to July 2023.\nEvaluation Results'),
 Document(id='60adb40f-c0b8-417d-8071-74c08e554efe', metadata={'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'trapped': '/False', 'producer': 'pdfTeX-1.40.25', 'page': 2, 'start_index': 0, 'paper': 'Llama 2', 'keywords': '', 'author': '', 'organization': 'Meta', 'subject': '', 'document_type': 'research_paper', 'title': '', 'page_label': '3', 'creationdate': '2023-07-20T00:30:36+00:00', 'total_pages': 77, 'chunk_id': 'llama2-page-3-chunk-6', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'year': 2023, 'access_level': 'public', 'moddate': '2023-07-20T00:30:36+00:00', 'paper_page': 3, 'section': 'introduction', 'creator': 'LaTeX with hyperref'}, page_content='Figure 1: Helpfulness human evaluationresults forLlama\n2-Chatcompared to other open-source and closed-source\nmodels. Human raters compared model generations on ~4k\nprompts consisting of both single and multi-turn prompts.\nThe95%confidenceintervalsforthisevaluationarebetween\n1% and 2%. More details in Section 3.4.2. While reviewing\nthese results, it is important to note that human evaluations\ncanbenoisyduetolimitationsofthepromptset,subjectivity\nof the review guidelines, subjectivity of individual raters,\nand the inherent difficulty of comparing generations.\nFigure 2: Win-rate % for helpfulness and\nsafety between commercial-licensed base-\nlines andLlama 2-Chat, according to GPT-\n4. To complement the human evaluation, we\nused a more capable model, not subject to\nour own guidance. Green area indicates our\nmodelisbetteraccordingtoGPT-4. Toremove\nties, we usedwin/(win + loss). The orders in\nwhich the model responses are presented to\nGPT-4arerandomlyswappedtoalleviatebias.\n1 Introduction'),
 Document(id='9112aec1-1f56-4d7d-89bc-2ab66e9093f8', metadata={'subject': '', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'moddate': '2023-07-20T00:30:36+00:00', 'chunk_id': 'llama2-page-19-chunk-79', 'creator': 'LaTeX with hyperref', 'trapped': '/False', 'year': 2023, 'access_level': 'public', 'author': '', 'paper': 'Llama 2', 'page_label': '19', 'producer': 'pdfTeX-1.40.25', 'keywords': '', 'document_type': 'research_paper', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'title': '', 'page': 18, 'total_pages': 77, 'creationdate': '2023-07-20T00:30:36+00:00', 'start_index': 0, 'organization': 'Meta', 'paper_page': 19, 'section': 'fine_tuning'}, page_content='Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels\nacross ~4,000 helpfulness prompts with three raters per prompt.\nThe largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of\n36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat\nmodel by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.\nInter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent\nassessments for each model generation comparison. High IRR scores (closer to 1.0) are typically seen as\nbetter from a data quality perspective, however, context is important. Highly subjective tasks like evaluating\nthe overall helpfulness of LLM generations will usually have lower IRR scores than more objective labelling\ntasks. There are relatively few public benchmarks for these contexts, so we feel sharing our analysis here will'),
 Document(id='e28b94f8-466c-4676-854b-474f49de47fa', metadata={'chunk_id': 'llama2-page-77-chunk-339', 'keywords': '', 'paper': 'Llama 2', 'title': '', 'year': 2023, 'total_pages': 77, 'paper_page': 77, 'subject': '', 'author': '', 'access_level': 'public', 'trapped': '/False', 'moddate': '2023-07-20T00:30:36+00:00', 'page': 76, 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'document_type': 'research_paper', 'producer': 'pdfTeX-1.40.25', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'page_label': '77', 'start_index': 851, 'creationdate': '2023-07-20T00:30:36+00:00', 'organization': 'Meta', 'section': 'appendix', 'creator': 'LaTeX with hyperref'}, page_content='License A custom commercial license is available at:ai.meta.com/resources/\nmodels-and-libraries/llama-downloads/\nWhere to send com-\nments\nInstructions on how to provide feedback or comments on the model can be\nfound in the model README, or by opening an issue in the GitHub repository\n(https://github.com/facebookresearch/llama/).\nIntended Use\nIntended Use CasesLlama 2is intended for commercial and research use in English. Tuned models\nare intended for assistant-like chat, whereas pretrained models can be adapted\nfor a variety of natural language generation tasks.\nOut-of-Scope UsesUse in any manner that violates applicable laws or regulations (including trade\ncompliance laws). Use in languages other than English. Use in any other way\nthat is prohibited by the Acceptable Use Policy and Licensing Agreement for\nLlama 2.\nHardware and Software(Section 2.2)\nTraining Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-'),
 Document(id='d6b0511a-829f-411b-8c6c-45a9c952ffc3', metadata={'page': 76, 'producer': 'pdfTeX-1.40.25', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'trapped': '/False', 'section': 'appendix', 'start_index': 2433, 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'chunk_id': 'llama2-page-77-chunk-341', 'page_label': '77', 'paper': 'Llama 2', 'subject': '', 'title': '', 'moddate': '2023-07-20T00:30:36+00:00', 'organization': 'Meta', 'access_level': 'public', 'author': '', 'paper_page': 77, 'total_pages': 77, 'keywords': '', 'document_type': 'research_paper', 'year': 2023}, page_content='nor the fine-tuning datasets include Meta user data.\nData Freshness The pretraining data has a cutoff of September 2022, but some tuning data is\nmore recent, up to July 2023.\nEvaluation Results\nSee evaluations for pretraining (Section 2); fine-tuning (Section 3); and safety (Section 4).\nEthical Considerations and Limitations(Section 5.2)\nLlama 2is a new technology that carries risks with use. Testing conducted to date has been in\nEnglish, and has not covered, nor could it cover all scenarios. For these reasons, as with all LLMs,\nLlama 2’s potential outputs cannot be predicted in advance, and the model may in some instances\nproduce inaccurate or objectionable responses to user prompts. Therefore, before deploying any\napplications ofLlama 2, developers should perform safety testing and tuning tailored to their\nspecific applications of the model. Please see the Responsible Use Guide available available at\nhttps://ai.meta.com/llama/responsible-user-guide\nTable 52: Model card forLlama 2.'),

In [83]:
display_documents(
    initial_candidates,
    title="Before Reranking: Initial Vector Candidates",
    max_documents=10,
)

====================================================================================================
Before Reranking: Initial Vector Candidates
====================================================================================================

RANK: 1
Paper page: 10
Section: fine_tuning
Chunk ID: llama2-page-10-chunk-38
----------------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latest

RANK: 2
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 3
Paper page: 11
Section: fine_tuning
Chunk ID: llama2-page-11-chunk-45
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 4
Paper page: 18
Section: fine_tuning
Chunk ID: llama2-page-18-chunk-77
----------------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for ju

RANK: 5
Paper page: 51
Section: appendix
Chunk ID: llama2-page-51-chunk-230
----------------------------------------------------------------------------------------------------
time and the annotators also become more familiar with the tasks and thus have better work efficiency. We
also intentionally collect more multi-turn samples to increase the complexity of RLHF data and thus the
average number of tokens per sample also increase accordingly over batches.
In Figure 25, we plot out the preference rating change over batches. It can be clearly seen that the share
of samples with similar responses (e.g.,negligibly better or unsure) increase dramatically over time while
those with stronger preference (e.g.,significantly better) drop in the meantime. This reflects the n

RANK: 6
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

RANK: 7
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-340
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2was pretrained on 2 trillion tokens of data from publicly

RANK: 8
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-6
----------------------------------------------------------------------------------------------------
Figure 1: Helpfulness human evaluationresults forLlama
2-Chatcompared to other open-source and closed-source
models. Human raters compared model generations on ~4k
prompts consisting of both single and multi-turn prompts.
The95%confidenceintervalsforthisevaluationarebetween
1% and 2%. More details in Section 3.4.2. While reviewing
these results, it is important to note that human evaluations
canbenoisyduetolimitationsofthepromptset,subjectivity
of the review guidelines, subjectivity of individual raters,
and the inherent difficulty of comparing generations.
Figure 2: Win-rate % for helpfulness

RANK: 9
Paper page: 19
Section: fine_tuning
Chunk ID: llama2-page-19-chunk-79
----------------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generatio

RANK: 10
Paper page: 77
Section: appendix
Chunk ID: llama2-page-77-chunk-339
----------------------------------------------------------------------------------------------------
License A custom commercial license is available at:ai.meta.com/resources/
models-and-libraries/llama-downloads/
Where to send com-
ments
Instructions on how to provide feedback or comments on the model can be
found in the model README, or by opening an issue in the GitHub repository
(https://github.com/facebookresearch/llama/).
Intended Use
Intended Use CasesLlama 2is intended for commercial and research use in English. Tuned models
are intended for assistant-like chat, whereas pretrained models can be adapted
for a variety of natural language generation tasks.
Out-of-Scope UsesUse in any man

In [84]:
reranked_documents = reranking_retriever.invoke(reranking_query)

In [85]:
display_documents(
    reranked_documents,
    title="After Reranking: Final Top Documents",
    max_documents=5,
)

====================================================================================================
After Reranking: Final Top Documents
====================================================================================================

RANK: 1
Paper page: 10
Section: fine_tuning
Chunk ID: llama2-page-10-chunk-38
----------------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latest

RANK: 2
Paper page: 11
Section: fine_tuning
Chunk ID: llama2-page-11-chunk-45
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 3
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-14
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 4
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

RANK: 5
Paper page: 51
Section: appendix
Chunk ID: llama2-page-51-chunk-230
----------------------------------------------------------------------------------------------------
time and the annotators also become more familiar with the tasks and thus have better work efficiency. We
also intentionally collect more multi-turn samples to increase the complexity of RLHF data and thus the
average number of tokens per sample also increase accordingly over batches.
In Figure 25, we plot out the preference rating change over batches. It can be clearly seen that the share
of samples with similar responses (e.g.,negligibly better or unsure) increase dramatically over time while
those with stronger preference (e.g.,significantly better) drop in the meantime. This reflects the n

User query
     ↓
Dense Retriever
     ↓
Top 20 candidates
     ↓
Cross-Encoder Reranker
     ↓
Query-document relevance evaluation
     ↓
Final top 5 documents

In [86]:
bm25_retriever.k = 15

In [87]:
dense_candidate_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 15
    },
)

In [88]:
hybrid_candidate_retriever = EnsembleRetriever(
    retrievers=[
        bm25_retriever,
        dense_candidate_retriever,
    ],
    weights=[
        0.5,
        0.5,
    ],
)

In [89]:
hybrid_reranking_retriever = ContextualCompressionRetriever(
    base_retriever=hybrid_candidate_retriever,
    base_compressor=cross_encoder_reranker,
)

In [90]:
query = (
    "What techniques did Meta use to improve the helpfulness and safety of Llama 2-Chat?"
)

In [91]:
final_documents = hybrid_reranking_retriever.invoke(query)

In [92]:
final_documents

[Document(metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public', 'start_index': 823, 'chunk_id': 'llama2-page-1-chunk-1'}, page_content='Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang\nAngela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic\nSergey Edunov Thomas Scialom∗\nGenAI, Meta\nAbstract\nIn this work, we develop and release Llama 2, a collection of pretrained and fine-tuned\nlarge language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.\nOur fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our\nmodels outperform open-source chat models on most benchmarks we tested, and based on\nour human evaluations for helpfulness and safety, may be a suitable substitute for closed-\nsource models. We provide a detailed description of our approach to fine-tuning and safety\nimprovements ofLlama 2-Chat in order to enable the community to build on our work and\ncontribute to the responsible development of LLMs.\n∗Equal contribution, corresponding authors: {tscialom, htouvron}@meta.com\n†Second author'),
 Document(metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 2, 'page_label': '3', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 3, 'section': 'introduction', 'access_level': 'public', 'start_index': 2540, 'chunk_id': 'llama2-page-3-chunk-9'}, page_content='the community to advance AI alignment research.\nIn this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and\nLlama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,\nLlama 2-Chat models generally perform better than existing open-source models. They also appear to\nbe on par with some of the closed-source models, at least on the human evaluations we performed (see\nFigures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data\nannotation and tuning, as well as conducting red-teaming and employing iterative evaluations. Additionally,\nthis paper contributes a thorough description of our fine-tuning methodology and approach to improving\nLLM safety. We hope that this openness will enable the community to reproduce fine-tuned LLMs and\ncontinue to improve the safety of those models, paving the way for more responsible development of LLMs.'),
 Document(id='93751005-fc01-4c82-84cc-4aa90b8af5e6', metadata={'start_index': 1540, 'access_level': 'public', 'document_type': 'research_paper', 'paper_page': 4, 'total_pages': 77, 'year': 2023, 'author': '', 'organization': 'Meta', 'title': '', 'moddate': '2023-07-20T00:30:36+00:00', 'keywords': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'creator': 'LaTeX with hyperref', 'paper': 'Llama 2', 'page': 3, 'subject': '', 'chunk_id': 'llama2-page-4-chunk-13', 'section': 'introduction', 'page_label': '4', 'producer': 'pdfTeX-1.40.25', 'creationdate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5'}, page_content='Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover\nall scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform\nsafety testing and tuning tailored to their specific applications of the model. We provide a responsible use\nguide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of\nour responsible release strategy can be found in Section 5.3.\nThe remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology\n(Section 3), approach to model safety (Section 4), key observations and insights (Section 5), relevant related\nwork (Section 6), and conclusions (Section 7).\n‡https://ai.meta.com/resources/models-and-libraries/llama/\n§We are delaying the release of the 34B model due to a lack of time to sufficiently red team.\n¶https://ai.meta.com/llama\n‖https://github.com/facebookresearch/llama\n4'),
 Document(metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 34, 'page_label': '35', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 35, 'section': 'discussion', 'access_level': 'public', 'start_index': 778, 'chunk_id': 'llama2-page-35-chunk-150'}, page_content='deployment as described in ourResponsible Use Guide.§§\n5.3 Responsible Release Strategy\nRelease Details. We makeLlama 2 available for both research and commercial use athttps://ai.meta.\ncom/resources/models-and-libraries/llama/. Those who useLlama 2 must comply with the terms of\nthe provided license and ourAcceptable Use Policy, which prohibit any uses that would violate applicable\npolicies, laws, rules, and regulations.\nWe also provide code examples to help developers replicate our safe generations withLlama 2-Chatand\napply basic safety techniques at the user input and model output layers. These code samples are available\nhere: https://github.com/facebookresearch/llama. Finally,wearesharinga ResponsibleUseGuide ,which\nprovides guidelines regarding safe development and deployment.\nResponsible Release. While many companies have opted to build AI behind closed doors, we are releasing\nLlama 2 openly to encourage responsible AI innovation. Based on our experience, an open approach draws'),
 Document(metadata={'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'D:\\complete_content_new\\Full-Stack-GenAI-Bootcamp-1.0\\Class-36-29-July-2026-Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 2, 'page_label': '3', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 3, 'section': 'introduction', 'access_level': 'public', 'start_index': 3414, 'chunk_id': 'llama2-page-3-chunk-10'}, page_content='continue to improve the safety of those models, paving the way for more responsible development of LLMs.\nWe also share novel observations we made during the development ofLlama 2 and Llama 2-Chat, such as\nthe emergence of tool usage and temporal organization of knowledge.\n3')]

In [93]:
display_documents(
    final_documents,
    title="Hybrid Retrieval + Cross-Encoder Reranking",
    max_documents=5,
)

====================================================================================================
Hybrid Retrieval + Cross-Encoder Reranking
====================================================================================================

RANK: 1
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

RANK: 2
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 3
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-13
----------------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), a

RANK: 4
Paper page: 35
Section: discussion
Chunk ID: llama2-page-35-chunk-150
----------------------------------------------------------------------------------------------------
deployment as described in ourResponsible Use Guide.§§
5.3 Responsible Release Strategy
Release Details. We makeLlama 2 available for both research and commercial use athttps://ai.meta.
com/resources/models-and-libraries/llama/. Those who useLlama 2 must comply with the terms of
the provided license and ourAcceptable Use Policy, which prohibit any uses that would violate applicable
policies, laws, rules, and regulations.
We also provide code examples to help developers replicate our safe generations withLlama 2-Chatand
apply basic safety techniques at the user input and model output layers. Th

RANK: 5
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-10
----------------------------------------------------------------------------------------------------
continue to improve the safety of those models, paving the way for more responsible development of LLMs.
We also share novel observations we made during the development ofLlama 2 and Llama 2-Chat, such as
the emergence of tool usage and temporal organization of knowledge.
3

                         ┌── BM25 Search ───────┐
User query ──────────────┤                      ├── Weighted RRF
                         └── Dense Search ──────┘
                                                   ↓
                                          Candidate documents
                                                   ↓
                                       Cross-Encoder Reranker
                                                   ↓
                                           Final top documents

Sparse Retrieval
    = BM25Retriever

Dense Retrieval
    = VectorStoreRetriever

Hybrid Retrieval
    = BM25 + Dense + EnsembleRetriever + Weighted RRF

Query Rewriting
    = Convert a contextual query into a standalone query

Query Expansion
    = Generate related query variations and merge their results

Query Decomposition
    = Split one complex query into atomic searchable queries

HyDE
    = Generate a hypothetical answer passage and use its embedding for dense retrieval

Reranking
    = Retrieve broad candidates and reorder them using a cross-encoder

1. BM25 sparse retrieval
2. Dense vector retrieval
3. Hybrid retrieval
4. Query rewriting
5. Query expansion
6. Query decomposition
7. HyDE retrieval
8. Dense retrieval + reranking
9. Hybrid retrieval + reranking

HOME_WORK
weighted fusion
resiporcal rank fusion
multi query retriever
Multi hop retriever
parenet document retriever
sentence window retriever
contextual compression

CUSTOM_RETRIEVER
Langchain 
langchain provide one baseretriever class ontop of it you can create custom retriever with your own logic(when you are usingh langchain/langgraph)

In [ ]:
i will take one more hour reteriever
will discuss about the prompting

In [ ]:
# from langchain_openai import ChatOpenAI
# from langchain_core.prompts import ChatPromptTemplate

# llm = ChatOpenAI(
#     model="gpt-4.1-mini",
#     temperature=0
# )

# hyde_prompt = ChatPromptTemplate.from_messages(
#     [
#         (
#             "system",
#             """
# Generate a short hypothetical document that could answer
# the user's question.

# Do not mention that the document is hypothetical.
# Write it in the style of a factual knowledge-base passage.
# """
#         ),
#         (
#             "human",
#             "{query}"
#         )
#     ]
# )

# query = "How does Llama 2 improve safety?"

# response = llm.invoke(
#     hyde_prompt.format_messages(
#         query=query
#     )
# )

# hypothetical_document = response.content

# print("Original Query:")
# print(query)

# print("\nHypothetical Document:")
# print(hypothetical_document)


# hyde_vector = base_embeddings.embed_query(
#     hypothetical_document
# )

# hyde_documents = vector_store.similarity_search_by_vector(
#     hyde_vector,
#     k=4
# )

# for i, document in enumerate(hyde_documents, start=1):
#     print("=" * 80)
#     print(f"RESULT {i}")
#     print(document.page_content[:1000])

multimodal RAG builder
full flede project

MEGA ASSISGNMENT on Sunday